### ISSUE TITLE
AbstractState in Mathematica

### ISSUE THREAD

**Issue by shrx** [CoolProp/CoolProp#1008]
Is it possible to create an `AbstractState` instance with the Mathematica wrapper? I would like to create some melting line plots, and as far as I know the low-level interface is needed to access the `melting_line` properties (found the python example for water here: http://www.coolprop.org/dev/coolprop/HighLevelAPI-1.py ).

**Comment by jowr** [comment]
The wrapper (https://github.com/CoolProp/CoolProp/blob/master/wrappers/Mathematica/CoolPropMathematica.cpp) is very basic since none of the core developers has access to Mathemtica. Feel invited to add more functionality. I think this is what you want: http://www.coolprop.org/coolprop/LowLevelAPI.html#access-from-high-level-interface

**Comment by shrx** [comment]
Thanks, will check it out.

**Comment by ibell** [comment]
Bump.  
a) Did you get this working?
b) Can you please provide your code if you did so that others can learn from your experience?

**Comment by shrx** [comment]
Unfortunately I am quite busy at work, so I didn't have any free time to start studying the code. I am afraid you can't count on me to make something useful of it in the near future.

**Comment by ibell** [comment]
Too bad...  I'll close the issue for now, feel free to revisit it.
