### ISSUE TITLE
Sphinx builder

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1029]
The development version of the docs looks quite different from what it used to look like. Did the buildbot change? Did anyone update the templates? We should verify that the docs are readable before we release a new version.

**Comment by ibell** [comment]
I think it's the sphinx version, otherwise nothing has changed.  1.2.3 is
used for 5.1.2, and 1.3.5 is used for dev.  Overall I think I like their
changes, but I have some weirdness when I look at the docs at work.  I'll
send a screenshot to show you.

Also, I'm getting random weird failures/crashes(!) when I try to compile
the docs.  I'll look into it this weekend.

**Comment by ibell** [comment]
I think the issues are all resolved.  It looks fine on my PC.

**Comment by ibell** [comment]
But it certainly does look funky on firefox. Hmm...

![capture_24042016_223233](https://cloud.githubusercontent.com/assets/1859947/14773861/9ccb9e54-0a6c-11e6-9567-d6e6ed569f5c.png)

**Comment by ibell** [comment]
Any idea why the logo is scaled weirdly?
