### ISSUE TITLE
a858417 follow-up: use CoolProp::set_error_string() instead of returning error string in get_parameter_information_string()

### ISSUE THREAD

**Issue by mikekaganski** [CoolProp/CoolProp#1096]
Previously, get_parameter_information_string() used to return its error string in its result buffer. This was the case long ago, at least since 9299cb8e073bef6254815ed2e49db096be555ca8.

This is a problem in wrappers:
some of them (like SMath) detect error return code (0) and ignore the returned buffer contents;
others (like Julia by @JonWel ) seem to ignore the returned code, but instead always return the buffer contents, thus disallowing programmatic detection of the error.

The proposal is to follow the practice of using CoolProp::set_error_string() for that. If a wrapper still needs the previous behaviour, then it may use get_global_param_string("errstring").

**Comment by JonWel** [comment]
I should in deed makes the Julia wrapper read the value returned by the function (`0` or `1`), and display the message as an error instead of as an answer when the value returned is `0`. I don't know why I didn't thought about doing so when making the wrapper for this function (one of my first work on this wrapper was to add error handling).

Throwing the error in `CoolProp::set_error_string()` could make the library a bit more consistent in the process to set the error (each time there is an error, the error message is in the `get_global_param_string("errstring")`).
@ibell do you want me to change the way errors are returned by `get_parameter_information_string()`?

**Comment by mikekaganski** [comment]
@JonWel , I made a pull request that takes care of the issue on the library level; I suppose that you may make Julia part.
