### ISSUE TITLE
Mass-based properties don't work for cubic backends

### ISSUE THREAD

**Issue by ianhbell** [CoolProp/CoolProp#1124]
```python
import CoolProp.CoolProp as CP, numpy as np, matplotlib.pyplot as plt

for fluid in ['PROPANE']:
    Ts = np.linspace(100, 290)
    rhoL = CP.PropsSI('D','T',Ts,'Q',0,'REFPROP::'+fluid)
    rhoL_PR = CP.PropsSI('D','T',Ts,'Q',0,'PR::'+fluid)
    rhoL_SRK = CP.PropsSI('D','T',Ts,'Q',0,'SRK::'+fluid)
    plt.plot(Ts, rhoL, label = 'REFPROP')
    plt.plot(Ts, rhoL_PR, label = 'PR')
    plt.plot(Ts, rhoL_SRK, label = 'SRK')
plt.legend()
plt.show()
```

**Comment by JonWel** [comment]
The molar mass it outputted as 0:
```Julia
PropsSI("molarmass", "PR::water")
0.0
```

**Comment by JonWel** [comment]
Yes, molar mass is not computed because the function "HelmholtzEOSMixtureBackend::set_components" is not called in the cubic backend.
Thus `components` is null, and iterating over it's size keep the molar mass to 0.

Maybe the simplest would be to add `components = fluid_identifiers;` in the constructor of the cubics?

**Comment by JonWel** [comment]
So, in `CubicBackend.h`, adding the include:
```C++
#include "Backends/Helmholtz/Fluids/FluidLibrary.h"
```
And adding these lines to the constructor of the PR and SRK:
```C++
    N = fluid_identifiers.size();
    components.resize(N);
    for (unsigned int i = 0; i < N; ++i){
        components[i] = get_library().get(fluid_identifiers[i]);
    }
```
Gives a value for molar mass.

@ianhbell  Do you have a better Idea?

**Comment by ibell** [comment]
Yes, I do have a better idea :) 

The JSON schema for the cubics defines the molar mass, therefore we should load the molar mass from the JSON file when we are loading the critical point parameters for the cubics and use that.  Loading from HEOS backend, which while in principle is fine, will fail if you have a fluid that is not also in CoolProp.  Can you put together a PR?  There are a few bits and pieces you will need to get working.

**Comment by JonWel** [comment]
I agree with your suggestion.

However I'm not sure how to proceed (I never worked with these JSON files).

Do I have to create cubic's own `Fluids/FluidLibrary.cpp` with only the functions of interest?
Can't we reuse the source code directly with some simple changes like `#include "all_fluids_JSON.h"` -> `#include "all_cubics_JSON.h"`?
Possibility to make a child?
```C++
static JSONCubicLibrary JSONFluidLibrary;
```

**Comment by ibell** [comment]
Evidently the mole mass does get read from the JSON already:
https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/CubicsLibrary.cpp#L33

It's a bit trickier though since when you pass fluid names to the cubic
backends, it does this:
https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/CubicBackend.h#L198
(the molar masses are not used)

So we would need to store the mole masses in the AbstractCubicBackend and
re-implement calc_molar_mass.  In principle that's only a few lines of
code.  You could steal the code for that from the HEOS backend.

**Comment by JonWel** [comment]
Ok, I'll try to fix that tomorrow.
This looks way more clear now :)
