### ISSUE TITLE
4.x runs faster than 5.x

### ISSUE THREAD

**Issue by bo3mrh** [CoolProp/CoolProp#1154]
@ibell 

This is regarding the speed issue on the high level that we discussed about in Purdue conference.

**Comment by jowr** [comment]
I do not know what you discussed, but this issue has already been mentioned once or twice on the mailing list. I would assume, that the new code is slower because there are many more objects that interact and because of the heavy use of inheritance. 

Could you share some more details? I am curious to hear about your discussion...

**Comment by ibell** [comment]
I think the problem is that before there was the ``UseSaturationLUT()`` function, and now that doesn't exist anymore, and therefore the calls to saturation are super slow.  The code of ACHP is much slower with version 5/6 of CoolProp.

**Comment by ibell** [comment]
Can we close this one now?  I think the changes in ACHP make this issue obsolete.  We should still see about tabular interpolation though...

**Comment by bo3mrh** [comment]
Sure. 
It would be great if we could use the tabular interpolation.

**Comment by thorade** [comment]
Can we close this one now? Sure.
I'll click the close button then.
Feel free to reopen.
