### ISSUE TITLE
PropertyPlot not working

### ISSUE THREAD

**Issue by GloriaVictis** [CoolProp/CoolProp#1167]
Using CoolProp (6.0.0) Python wrapper.
```
from CoolProp.Plots import PropertyPlot
plot = PropertyPlot('Helium', 'TS')
plot.show()
```

Simply yields an empty plot.
![tsfail](https://cloud.githubusercontent.com/assets/7292165/17095302/17c363ec-5254-11e6-857c-193d9dc52ef5.png)

**Comment by jowr** [comment]
This is the correct behaviour since you have not added any lines to the plot. See http://coolprop.sourceforge.net/dev/coolprop/python-plotting.html for a preview of the features for the next release (6.0.1). 

```Python
from CoolProp.Plots import PropertyPlot
plot = PropertyPlot('Helium', 'TS')
plot.calc_isolines()
plot.show()
```

![figure_1](https://cloud.githubusercontent.com/assets/769593/17096544/213d72ae-525a-11e6-8b72-8b9cec328958.png)
