### ISSUE TITLE
Mixture Water-Ammonia

### ISSUE THREAD

**Issue by erlen07** [CoolProp/CoolProp#1223]
This mixture is very common in absorption chillers.
Can it be included in your binary pair data base?

**Comment by ibell** [comment]
We have liquid-phase ammonia water: http://www.coolprop.org/fluid_properties/Incompressibles.html#id178

But the full mixture model is not provided, I am actively working on developing that model in my day job.  The current ammonia+water mixture model is not compatible with other mixture models, which is why we have not implemented it.
