### ISSUE TITLE
IF97 Backend Improvements Question

### ISSUE THREAD

**Issue by henningjp** [CoolProp/CoolProp#1313]
This is a coding question as I work on providing additional input pairs for the IF97 Backend.

It looks like the other backends, say for a PQ or QT input pair, use Update() to calculate as many values are can be evaluated given the input pair provided.  The calls to the calc_ routines (calc_T, calc_pressure, calc_hmass, etc.) then just return the cached values.  Please correct me if I'm mis-understanding this.

The goal of the IF97 routines is to be **_fast_**.  I don't want to calculate and cache a lot of values if they aren't being asked for by the user/calling program;  I want the bare minimum number of calls to IF97 to deliver the results asked for.   So I think there needs to be logic inside each of the calc_ routines to determine which IF97 routine to call based on the input pairs.  

Is there a way to determine the input pairs when the INPUT_PAIRS parameter isn't passed into the virtural calc_ routines?  I tried examining the cached values using the bool() operator to see if they are set, but that didn't seem to work.

        double calc_hmass(void){
             if (bool(_p) && bool(_Q)) { ... } else { ... }         // I always get the else branch
        }

If there's an example of how to do this in one of the other backends, that would be great!

**Comment by ibell** [comment]
I think the best approach is to set the ``_phase`` flag after update is called.  That way you can fork and do the right thing and minimize the amount of calls to do.  You might also want to consider storing the region number so that you can skip the phase evaluation.  That is my idea about what the flow looks like:

1) In update, do the calculation, store all the variables that are needed, the phase flag, and the region
2) In calc_XXX function, use cached values of region, T, p, phase to determine how to update the class, cache the new value

Note: make sure that you overload the clear() function and clear any variables you have set and then do the same for base class, see for instance: http://www.coolprop.org/_static/doxygen/html/_helmholtz_e_o_s_mixture_backend_8h_source.html#l00072

**Comment by henningjp** [comment]
OK.  It's clicking; especially after browsing the REFPROP backend again.  Also, I was calling the bool() operator incorrectly anyway.  I think I'm on the right track now.  Thanks.

**Comment by ibell** [comment]
Ok, good to hear!
