### ISSUE TITLE
Simulation error when using ExternalMedia in Dymola

### ISSUE THREAD

**Issue by LogikSun** [CoolProp/CoolProp#1350]
I am new to Modelica. I have setup ExternalMedia (CoolProp2Modelica) as the steps. But when I ran the test programs. The compiler went wrong with these messages:

msvcprt.lib(locale0_implib.obj) : error LNK2038: “_MSC_VER”No match item: value“1800”is unmatched with “1700”(ExternalMediaLib.lib(externalmedialib.obj) )
ExternalMediaLib.lib(CPState.obj) : error LNK2001: Unresolved external symbol "__declspec(dllimport) class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::endl(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_?endl@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@1@AAV21@@Z)
ExternalMediaLib.lib(FluidClass.obj) : error LNK2001: Unresolved external symbol "__declspec(dllimport) class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::endl(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_?endl@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@1@AAV21@@Z)

what should do with these? Thank you very much.

**Comment by jowr** [comment]
Hi, this is most certainly the wrong place for your request. If you use CoolProp version 5 or 6, please refer to https://github.com/CoolProp/ExternalMedia. In case you are using CoolProp 4, you should not need to recompile the library yourself since ExternalMedia comes with built-in support for CoolProp.

Your error message tells you that you are trying to a static library that was built with an older version of Visual Studio. In particular, you are trying to link a Visual Studio 2012 library (v1700) with a code that was compiled with Visual Studio 2013 (v1800). Change your Modelica compiler to Visual Studio 2012 to solve your issue.

**Comment by thorade** [comment]
Same question was asked in OpenModelica forum:
https://openmodelica.org/forum/default-topic/2038-simulation-error-when-using-externalmedia-in-dymola
