### ISSUE TITLE
CoolProp online vapor quality

### ISSUE THREAD

**Issue by inamdarharshad** [CoolProp/CoolProp#1391]
When:
pressure = 2680797.01 [Pa]
quality = 1.0 [-]
then:
saturation temperature = 317.441101703 [K]

But when:
pressure = 2680797.01 [Pa]
temperature = 345.65 [K]
then:
vapor quality = -1.0 [-]

Could the vapor quality output value be changed to show subcooled liquid as -1.0 and superheated vapor as something different?

**Comment by ibell** [comment]
Sadly, not really, because to ascertain whether the state is liquid or vapor requires a saturation flash call, which is quite expensive, and not worth it.  For pure fluids, you can easily look at the density and see how it compares to the critical density.  For mixtures, its not quite that straightforward.
