### ISSUE TITLE
Exception thrown (PHI0dll function is not available) while using first_partial_deriv call with Refprop backend.

### ISSUE THREAD

**Issue by avadhutmg** [CoolProp/CoolProp#1408]
32-bit C# DLL (downloaded on 23 January 2017)
Operating System - Windows 64-bit, 
C# 
REFPROP 9.1

I am getting an exception while using derivative function - first_partial_deriv using Refprop backend. 
Exception - PHI0dll function is not available in your version of REFPROP. Please upgrade
This works fine while using HEOS backend.
Is there something I am missing?
Thank you.

**Comment by ibell** [comment]
You need to update REFPROP to 9.1.1.  email me at ian.bell@nist.gov

On Feb 1, 2017 8:58 AM, "avadhutmg" <notifications@github.com> wrote:

32-bit C# DLL (downloaded on 23 January 2017)
Operating System - Windows 64-bit,
C#
REFPROP 9.1

I am getting an exception while using derivative function -
first_partial_deriv using Refprop backend.
Exception - PHI0dll function is not available in your version of REFPROP.
Please upgrade
This works fine while using HEOS backend.
Is there something I am missing?
Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CoolProp/CoolProp/issues/1408>, or mute the thread
