### ISSUE TITLE
about different between coolprop and refprop

### ISSUE THREAD

**Issue by birdol** [CoolProp/CoolProp#1483]
hi there.
my work is on heat xchange and air-conditioner, and my business partner used refprop for a long time , is good and great ,but not open source and cost so much.
my question is : is there any different form coolprop and refprop? when i use coolprop, the calc answer will get any different?

**Comment by ibell** [comment]
Well, REFPROP isn't really all that expensive...

CoolProp doesn't have as good coverage for mixtures as REFPROP (actually
much worse), and the algorithms for phase equilibrium for mixtures are much
worse than REFPROP.  Also, several unpublished transport property models
are missing in CoolProp versus REFPROP

Otherwise, CoolProp is in general, as good as or better than REFPROP in
terms of : ease of interface with a huge range of programming languages,
addition of psychrometric properties, incompressible fluids, etc.
