### ISSUE TITLE
Make VTPR thread safe

### ISSUE THREAD

**Issue by JonWel** [CoolProp/CoolProp#1494]
Currently, the instances of UNIFAC library are references of the library, which causes threading problem if more than one thread tried to access this library.
To allow safe threading, we need to make a copy of the library, so that each thread access it's own library.

The reference are defined [here](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/VTPRBackend.h#L42) and [here](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/VTPRBackend.h#L54), depending on how the backend is instantiated.

These create references of a same [lib instance](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/VTPRBackend.cpp#L12), which is causing the threading issue.

As far as I understand, removing the `&` in the two calls line [42](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/VTPRBackend.h#L42) and [54](https://github.com/CoolProp/CoolProp/blob/master/src/Backends/Cubics/VTPRBackend.h#L54) would create copies instead of references.

@ibell Do you have a MWE I can test to check this thread safe behaviour? (it can be in Python)
If not, I'll try to make one.

**Comment by ibell** [comment]
As it turns out, I think I was wrong; VTPR seems to be threadsafe.  I was using multiple instances in parallel without any problem recently (fitting).  They key is that the library is not **written** to by multiple instances.  Therefore, the reading should be no problem - reading is in general a thread-safe operation.
