### ISSUE TITLE
Add English Units

### ISSUE THREAD

**Issue by wlamont** [CoolProp/CoolProp#1507]
Nice work with CoolProp!  More of a feature request: please implement the english system units as well as SI, KSI and EUR.

**Comment by ibell** [comment]
For English units, I'm going to put on my BDFL
<https://en.wikipedia.org/wiki/Benevolent_dictator_for_life> hat and say
sorry, but no.  The SI variants I am not morally opposed to, and if you
wanted to add this as a pull request, I would consider it.  But I think
that the base SI set of units is the "best" set of units to work in because
there are NEVER any unit conversions.

**Comment by mikekaganski** [comment]
IMO, the unit conversion stuff is not the proper task for such a library. You can use specialized software for that (like SMath Studio or MathCad) that have the unit system built-in, and take great amount of effort to implement unit conversions properly and unambiguously.

**Comment by wlamont** [comment]
Fair enough.  I work for a rocket company and our default units are english.  Is there away to output say isolines to an array so I can scale them to other units?

**Comment by ibell** [comment]
REFPROP's dll is also in SI units :)  But you can do diagrams in REFPROP GUI in your units, and then output the lines to a file from the REFPROP GUI

**Comment by thorade** [comment]
If you are using Python you could even try one of the existing unit conversion libraries, e.g. first result on Google:
http://pint.readthedocs.io/en/latest/systems.html

**Comment by ibell** [comment]
Or the quantities package is quite nice too

**Comment by thorade** [comment]
BDFL says no, so closing for now.
Please reopen if there is any further action required.
