### ISSUE TITLE
Unify AbstractState's behavior when using HEOS or the tabular interpolations schemes

### ISSUE THREAD

**Issue by andfranklin** [CoolProp/CoolProp#1563]
I am receiving errors or wrong answers when using either `BICUBIC` or `TTSE` interpolation schemes. Here is a minimal example:

```python
import CoolProp
import sys

from CoolProp import AbstractState
from CoolProp import HmassP_INPUTS
from CoolProp import iphase_gas, iphase_liquid

formulation = "HEOS"
# formulation = "TTSE&HEOS"
# formulation = "BICUBIC&HEOS"
fluid = "water"
phase = iphase_liquid
# phase = iphase_gas

print("python version:\n", sys.version)
print()
print("CoolProp version:", CoolProp.__version__)
print()

# Properties for saturated water with:
# P = 15 MPa
# T = Tsat(~342.16 C)
enthalpy = 2110448.76
pressure = 15.0E6

props = AbstractState(formulation, fluid)
props.specify_phase(phase)
props.update(HmassP_INPUTS, enthalpy, pressure)


print("temperature:", props.T() - 273.15)
print("pressure   :", props.p())
```

The output for `HEOS`:
```
python version:
 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

CoolProp version: 6.0.0

temperature: 342.1553921917787
pressure   : 15000000.0
```

The output for `TTSE`:
```
python version:
 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

CoolProp version: 6.0.0

temperature: nan
pressure   : 15000000.0
```

The output for `BICUBIC`:
```
python version:
 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

CoolProp version: 6.0.0

Traceback (most recent call last):
  File "minimal_example.py", line 28, in <module>
    props.update(HmassP_INPUTS, enthalpy, pressure)
  File "CoolProp/AbstractState.pyx", line 81, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:16429)
  File "CoolProp/AbstractState.pyx", line 83, in CoolProp.CoolProp.AbstractState.update (CoolProp/CoolProp.cpp:16318)
ValueError: Cell is invalid and has no good neighbors for x = 38020.3, y= 1.5e+07
```
I receive the same issues when using `phase = iphase_gas`.

**Comment by henningjp** [comment]
Here's the problem:

Sat Liquid Enthalpy @15MPa: 1610200   {J/kg-K}
Sat Liquid Enthalpy @15MPa: 2610697   {J/kg-K}

Your enthalpy value is smack in the two-phase region at 2110448.76  {J/kg-K}

You can't use this two-phase enthalpy value **_and_** specify_phase(iphase_liquid) or specify_phase(iphase_gas).  This enthalpy doesn't exist in the either the liquid phase or the vapor phase.  If you just comment out your line that specifies the phase you get the result:
```
temperature: 342.1553921761497
pressure   : 15000000.0
```

Alternatively,  you could use the saturated enthalpy value and specify the correct phase, you get roughly the same answer for temperature (as expected) for both saturation points, but not the same answer for the other properties:
```python
h_satL = CP.PropsSI("H","P",15e6,"Q",0,"HEOS::Water")
print("Sat Liquid Enthalpy @15MPa:", h_satL)
h_satV = CP.PropsSI("H","P",15e6,"Q",1,"HEOS::Water")
print("Sat Liquid Enthalpy @15MPa:", h_satV)
print()
pressure = 15.0E6

props = AbstractState(formulation, fluid)
props.specify_phase(iphase_liquid)
props.update(HmassP_INPUTS, h_satL, pressure)

print("Using Saturated Liquid Enthalpy")
print("-------------------------------")
print("temperature:", props.T() - 273.15)
print("pressure   :", props.p())
print("density    :", props.rhomass())
print()

props = AbstractState(formulation, fluid)
props.specify_phase(iphase_gas)
props.update(HmassP_INPUTS, h_satV, pressure)

print("Using Saturated Vapor Enthalpy")
print("-------------------------------")
print("temperature:", props.T() - 273.15)
print("pressure   :", props.p())
print("density    :", props.rhomass())
```
gives
```
Sat Liquid Enthalpy @15MPa: 1610200.3974908292
Sat Liquid Enthalpy @15MPa: 2610697.1187380725

Using Saturated Liquid Enthalpy
-------------------------------
temperature: 342.1588690602118
pressure   : 15000000.0
density    : 603.5313806501864

Using Saturated Vapor Enthalpy
-------------------------------
temperature: 342.1557585026395
pressure   : 15000000.0
density    : 96.72730002706695
```

HEOS ignores your phase setting, realizes that it's a point in the two phase region and sets the Temperature value and report the two-phase mixture values for other properties as well.   However, the points for the mixture enthalpy with the the specified phase of liquid or gas do not exist in the tabular interpolation tables, so the interpolation fails.

**Comment by andfranklin** [comment]
Thank you for your response! That was a big help.

In this case the python interface is misleading. The behavior changes depending on whether or not you are using `HEOS` or one of the tabular interpolations.

Is there a way to quick way get the saturation properties for a given pressure or temperature? I could use the `HEOS` formulation like you did above, but this seems to be relatively expensive.

**Comment by henningjp** [comment]
Using low level interface for HEOS, as you are, just enter P and Q (1 or 0) and get T.  It should be fairly quick.

If you are just looking for Water and need speed, you might try the IF97 backend.  It works like HEOS for water, but the equations are all algebraic and fast.  It only suffers slightly on accuracy.  You'll need to download the 6.1.1dev version from the nightly build to get all the input pairs.

**Comment by andfranklin** [comment]
Thanks again! Your suggestion works and is very quick. I was able to come-up with an acceptable workaround because of your help.

I'll take a look at the IF97 backend. My application can definitely benefit from fast fluid property calculations.

**Comment by henningjp** [comment]
Yeah, I don't think this is really an issue.  HEOS is an equation of state; it has a backward formula in terms of  pressure and enthalpy in any phase region and can determine the state point.  Tabular interpolation is just that, interpolation within a table that is first calculated from HEOS.  Since the problem was over specified, the enthalpy value provided does not exist in the phase region requested in the table so it fails; it has no way to get to the correct state point without calling the HEOS, which defeats the purpose of a table lookup.

**Comment by andfranklin** [comment]
Maybe this isn't an issue, but the behavior differences between HEOS and the Tabular properties should at-least be documented. I can see the potential for other users getting frustrated that the Tabular interpolations schemes are behaving differently than HEOS and not knowing why. As far as I can tell there is no indication of these differences in the documentation.

**Comment by henningjp** [comment]
Looks like there are some opportunities in the code for some up-front range checking in the table interpolation backend to print some more sensible error messages.  I'll see what I can do.

**Comment by henningjp** [comment]
Checking for user set phase is not done in all input pair flash calculations, but it is in some, DmassT for example, in order to (optionally) speed up the flash calculation and will also yield weird errors if the user sets the phase incorrectly (two phase vs. single phase).  There are only some input pair flash calcs, the HmassP example above, where user set phase is ignored (either the option for speed-up was not implemented, or it didn't save much computational time).  Attempts to provide checking of the user specified phase simply slows things down.

I think the best way to handle this is to provide documentation on how, when, and why specifying the phase is done, with cautionary notes about setting it incorrectly for a given state point.  Setting the phase is optional (for speed in some cases) and should only be set if absolutely sure in what phase the state point resides.  The documentation example for the [Low-Level API](http://www.coolprop.org/coolprop/LowLevelAPI.html#things-only-in-the-low-level-interface) states this, but it could be clearer.
