### ISSUE TITLE
OCTAVE 32 bit for Windows

### ISSUE THREAD

**Issue by galtieri** [CoolProp/CoolProp#1576]
Please link library to a more recent version of Octave for Windows.

**Comment by ibell** [comment]
The general problem is your octave module that you compile always has to
match the version of octave you have, so that is a constantly moving
target.  For the MINGW octave builds, it is not too painful to build it
yourself, which, given our current manpower availability is sadly the only
option available.  If you wanted to update the build system to do that,
that would be fine with me.

**Comment by galtieri** [comment]
Done. If useful I can send the linked library for Octave 4.2.1 32 bit for Windows.
Please add to build instructions the following:
set OCTAVE_ROOT=c:\octave-4.2.1
set path=c:\MinGW;c:\octave-4.2.1\bin;c:\swigwin-3.0.12;%path%
... and before the last "cmake --build ." manually insert into file
CoolProp\build\CMakeFiles\CoolProp.dir\flags.make
the following
CXX_FLAGS =   -fpermissive  -std=gnu++11
as the -std=gnu++11 option is off by default.
Regards.
GA

**Comment by ibell** [comment]
And actually, the better approach would be to pass -DCMAKE_CXX_STANDARD=11
to the call to cmake.  Modifying files is almost always not the best option.

**Comment by galtieri** [comment]
It's true. I'm not a great expert in this field. I hope this can help other people that try to build the library themselves.

**Comment by ibell** [comment]
Can you file an update to the docs:
https://github.com/CoolProp/CoolProp/blob/master/Web/coolprop/wrappers/Octave/index.rst
please?
