### ISSUE TITLE
Pressure Output given Temperature and Enthalpy of a fluid-Error

### ISSUE THREAD

**Issue by TheodorosDimitriou** [CoolProp/CoolProp#1590]
Hello,

When trying to get the Pressure of a refrigerant when the Temperature and Enthalpy is given as an input, I am getting an error "This pair of inputs(HmassT_Inputs) is not yet supported.
Is there a way around this, or has anyone experience the same issue and what is the solution to overcome this?

The formula used (either in Excel or MathCAD) is PTh(ref,T,h)=PropsSI("P","T",T,"H",h,ref)

**Comment by ibell** [comment]
That is correct.  T,H are not supported inputs because there are multiple
solutions for a given pair of T,H coordinates sometimes, and there is/was
no easy way to handle that.  Besides, usually if you know T,H you know
something else, like P,H and can therefore do a P,H flash calculation

On Thu, Nov 9, 2017 at 5:13 AM, TheodorosDimitriou <notifications@github.com

**Comment by thorade** [comment]
Also see: https://pages.nist.gov/REFPROP-docs/#multiple-and-metastable-states
