### ISSUE TITLE
Infinite/Non existent values for Coolprops

### ISSUE THREAD

**Issue by ArRojas** [CoolProp/CoolProp#1592]
Hello all,

When I try to calculate enthalpy for the following list of values as: (they're already loaded in a df)
[P_T.xlsx](https://github.com/CoolProp/CoolProp/files/1466653/P_T.xlsx)

h = PropsSI('H', 'P', df['P'], 'T', df['T], 'R407C')

Im getting a gap between the enthalpy plot:
![figure_1](https://user-images.githubusercontent.com/33624408/32723852-44fc35fe-c86f-11e7-816c-0ea6cbb9c1ee.png)

Any clues why is this happening? Any help how to solve it?

Thank you very much!

**Comment by henningjp** [comment]
R407C is a mixture of three refrigerants: R32, R125 and R134a.  I suspect that in the area of your missing data, one or more of your components is flashing out or condensing giving you a two-phase mixture.  This is not supported for psuedo-pure fluids.  If you have the Excel add-in installed,  just insert the PropsSI() function in the next column in your Excel table, you will see that in the missing range, PropsSI() gives the result:
```
Two-phase inputs not supported for pseudo-pure for now : PropsSI("H","T",273.19,"P",472301.1,"R407C")
```

**Comment by ArRojas** [comment]
@henningjp 
Thanks your response.
So what you're saying is that unless I change the inlet parameters, I can't do much?
Thanks

**Comment by henningjp** [comment]
Unfortunately, yes.

**Comment by ibell** [comment]
Actually, the core problem in this case is that the pseudo-pure equations
of state are simply not valid inside the vapor-liquid equilibrium domain.
You could do a enthalpy-weighted average of the saturated liquid and vapor
states for the given pressure, but this is thermodynamically incorrect
(though in some cases it is good enough to do this).  REFPROP does this
thermodynamically incorrect analysis for instance. But CoolProp does not
because that treatment is wrong.

**Comment by ArRojas** [comment]
Thanks @ibell,

The data I'm using is supposed to be T and P of a superheated vapor, I guess I'll insert a max case between the enthalpy at vapor saturation and the one measured.

Thank you very much for your help :)
