### ISSUE TITLE
ValueError: calc_name is not implemented for this backend

### ISSUE THREAD

**Issue by davideziviani** [CoolProp/CoolProp#1616]
@ibell Tabular Backends

**Comment by jowr** [comment]
I guess the question is, what do you want to get? For HEOS you get the fluid name, for REFPROP you get the REFPROP file name - what would you expect for the tables? The name of the interpolation method? The fluid name of the underlying HEOS or REFPROP state class?

**Comment by ibell** [comment]
I'm here with them right now, the backed does not return the fluid name

**Comment by jowr** [comment]
Yes, but what do you want - the fluid name or the name of the interpolation scheme?

**Comment by ibell** [comment]
Just like the other backends, I think the name of the fluid.  Check HEOS
for instance

On Dec 8, 2017 8:24 AM, "Jorrit Wronski" <notifications@github.com> wrote:

Yes, but what do you want - the fluid name or the name of the interpolation
scheme?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CoolProp/CoolProp/issues/1616#issuecomment-350261995>,
or mute the thread

**Comment by jowr** [comment]
OK, please note that I added the function to HEOS only two weeks ago in a5309a3ecbb6f3ba8c6ecfcd84c46d718baf05e9 ... 

But just go ahead - I gues you cannot break anything.
