### ISSUE TITLE
Chemical potential with Dmolar and T inputs crashes python Kernel

### ISSUE THREAD

**Issue by L4student** [CoolProp/CoolProp#1653]
Chemical potential is not supported for mixtures if `Dmolar` and `T` are used as inputs.
`ValueError: DHSU_T_flash does not support mixtures (yet)`

If I only use one component as follows then it crashes the Kernel (`Kernel died, restarting`).
```
import CoolProp as CP
HEOS = CP.AbstractState("HEOS", "Water")
HEOS.update(CP.DmolarT_INPUTS, 1e-6, 323)
mu_w =  HEOS.chemical_potential(0)
```
If I only do `HEOS.chemical_potential` then it shows `<function chemical_potential>`, but I am not sure how this function returns output. Am I doing anything wrong?

**Comment by ibell** [comment]
Please open one issue per problem in the future - these are two separate issues

With regards to the first problem, as it says, D,T are not valid inputs for mixtures because the flash calculation has not been implemented in the HEOS backend.  If you know conclusively that your mixture is single-phase (not VLE), then you can specify any homogeneous phase and the flash calculation will be skipped.  For instance,

``` python
import CoolProp as CP
HEOS = CP.AbstractState("HEOS", "Methane&Ethane")
HEOS.set_mole_fractions([0.5,0.5])
HEOS.specify_phase(CP.iphase_gas)
HEOS.update(CP.DmolarT_INPUTS, 300, 323)
print(HEOS.chemical_potential(0))
```

For the second question, that is partly a bug in CoolProp - it should not crash if the mole fractions have been set (I'll fix that), and partly a misunderstanding.  The chemical potential of a pure fluid is equal to its molar Gibbs energy (See eq. 36 in my paper about humid air for more info: http://ws680.nist.gov/publication/get_pdf.cfm?pub_id=921756), therefore if you did instead 
```
import CoolProp as CP
HEOS = CP.AbstractState("HEOS", "Water")
HEOS.update(CP.DmolarT_INPUTS, 1e-6, 323)
mu_w = HEOS.gibbsmolar()
print(mu_w)
```
you would get the correct answer.

Hope that helps!

**Comment by ibell** [comment]
Your original attempt should work fine now too

**Comment by L4student** [comment]
Dear @ibell , thank you for your suggestions. I will take a look.
