### ISSUE TITLE
PH diagram difference using both coolprop and REFPROP

### ISSUE THREAD

**Issue by myjesus123** [CoolProp/CoolProp#1655]
first of all, using the python tool,
I compared PH diagram figure from coolprop with things that from refprop.
It seems that there are little bit error of enthalpy under same pressure value.

do you have any review?

**Comment by ibell** [comment]
Can you provide some specifics?  With that level of detail, it's impossible
to give you any assistance.

**Comment by thorade** [comment]
@myjesus123 All values are compared against Refprop automatically,
for example the checks for R134a are here:
http://www.coolprop.org/fluid_properties/fluids/R134a.html

The values for enthalpy will also depend on the reference state:
https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

I'll close this issue for now, because without additional information (e.g. what fluid, specification of inputs, expected output etc) it is not possible to help you.
If this still is an issue for you, please reopen!
