### ISSUE TITLE
UnsatisfiableError  (CoolProp with Miniconda on Win 10)

### ISSUE THREAD

**Issue by TheTinka** [CoolProp/CoolProp#1663]
I tried to install CoolProp with Anaconda and get: 
UnsatisfiableError: The following specifications were found to be in conflict:
  - coolprop
  - pycosat

Could someone help here?
Conda = 4,4.1
Python 3.6
Windows 10

**Comment by ibell** [comment]
The conda packages are basically not supported because the binary pip wheels are available for essentially all versions of Python and all platforms.  We recommend you install from the development server : http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation (second option)
