### ISSUE TITLE
change_EOS does not update backend_name

### ISSUE THREAD

**Issue by uqtredd1** [CoolProp/CoolProp#1702]
Found when working on the D wrapper, tested in both D-wrapped C++ and the python version. Simplest python code to reproduce:

```python
import CoolProp.CoolProp as CP

fluid = CP.AbstractState("HEOS","CO2")
fluid.backend_name() #  'HelmholtzEOSBackend'
fluid.change_EOS(0,"SRK")
fluid.backend_name() #  'HelmholtzEOSBackend', should be 'SRKBackend?
```
Calculating some properties shows that the backend has actually changed, just the backed_name has not been updated.

**Comment by ibell** [comment]
Ah, this is actually the correct behavior, but it's subtle.  Some explanation:

The HEOS backend uses the most accurate pure fluid EOS for each component in the mixture (here, a 1-component mixture, a pure fluid) plus a departure term (and some interaction parameters) to account for the fact that you have a mixture and the thermodynamics of a mixture need to be adjusted (I'll spare you some gory details, but can fill you in if you'd like).  When you call ``change_EOS`` what that does is for the given pure fluid in the mixture (still using the same backend), it replaces the high accuracy EOS with a cubic EOS of much lower accuracy.  This is, for instance, what was done in this paper: https://ws680.nist.gov/publication/get_pdf.cfm?pub_id=920895 .

If you truly want to use SRK (but why would you in this case?), you need to also switch the backend in the call to AbstractState so that the backend is switched in the low-level code.

That make sense?  Please feel free to ask for more clarification.
