### ISSUE TITLE
Surface Tension calculation failing ungracefully

### ISSUE THREAD

**Issue by emmaredfoot** [CoolProp/CoolProp#1745]
Do you want to ask a question? Are you looking for technical support? For any kind of question regarding CoolProp and its usage, you can ask the [CoolProp user group](https://goo.gl/Pa7FBT)

If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

Before posting an issue, please:  
    * Check the [CoolProp User Group](https://goo.gl/Pa7FBT) for common solutions.  
    * Check that your issue isn't already filed under [CoolProp Issues](https://github.com/CoolProp/CoolProp/issues).  
    * Check the CoolProp [latest release](http://www.coolprop.org) and [development version](http://www.coolprop.org/dev) documentation.  

### Description

Hello,

I have tried using both Props and PropsSI to calulate the surface tension.  I tried both 'I' and 'surface_tension' as the names of the output values. One example of an input is: PropsSI('surface_tension', 'T', 1500., 'D', 1, "Water"). I put in various temperatures, many much below the 1500 K shown here. I have tried using just temperature, temperature and pressure, as well as temperature and density as inputs.  Every time I get the error: ValueError: PropsSI failed ungracefully :: inputs were:"surface_tension","T",1.5000000000000000e+03,"D",1.0000000000000000e+00,"Water"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

### Steps to Reproduce

1. Import CoolProps PropsSI
2. Call for a surface tension calculation
3. run the code in terminal

**Expected behavior:** [What you expect to happen]

I expected the surface tension value to be returned

**Actual behavior:** [What actually happens]

ValueError: PropsSI failed ungracefully :: inputs were:"surface_tension","T",1.5000000000000000e+03,"D",1.0000000000000000e+00,"Water"; please file a ticket at https://github.com/CoolProp/CoolProp/issues

### Versions

**CoolProp Version:** 6.1.0
**Operating System and Version:**  MacOS High Sierra 10.13.6
**Access Method:** Python 2.7
### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by henningjp** [comment]
Surface tension only exists in the two phase region along the saturation curve.  You temp is way above the critical point.  Surface tension is not defined there.

Try a temperature between Tcrit and Ttriple.  Then call PropsSI at that temperature with a vapor quality of 0 or 1 (doesn’t matter which) to ensure you are on the saturation curve.  You should get surface tension returned there.

**Comment by henningjp** [comment]
Note, the dev version fails with a slightly more informative error message:
```
Temperature to QT_flash [  ] must be in range 273.06 K, 647.096 K
```
The second input key is ignored as well as it assumes the input key "T" is the saturation temperature.

**Comment by ibell** [comment]
Can we re-open please?  The issue is that if you have a statepoint that is
not two-phase, surface tension should not be evaluated in any case and a
more helpful message should be returned.

**Comment by henningjp** [comment]
@ibell So I have a patch ready, that checks the ``_phase`` in ``abstractstate::surface_tension()`` to make sure it's ``iphase_twophase`` and throws an exception with a reasonable error message if not.  It's one level up from ``calc_surface_tension()``, so should catch for all backends.  Unfortunately, the setting of ``_phase`` is not always accurate and might prevent calculation of surface tension when the state point actually IS two phase.  I can pick a pressure/temperature pair that I know are on the saturation curve and it still throws the error; it's probably picking _liquid_ or _vapor_ because it is **_on_** the saturation curve.  Is there a better way to do this?

Also, if an input pair contains P or T and something other than P or T, we have two choices:
- [ ] Just check the state and process accordingly.
- [ ] Assume that P or T is really Psat or Tsat (providing they are in range) and ignore the other input  

Do you have a vote?

**Comment by ibell** [comment]
My vote is that if _phase is two phase, you do the calculation, and if not,
throw an error.  Almost always if you want surface tension, you'll provide
PQ or TQ inputs.  And if in that case the phase *isn't* two phase, that's a
serious problem.
