### ISSUE TITLE
Issue with incompressible fluid in v6.2.1

### ISSUE THREAD

**Issue by DanWBR** [CoolProp/CoolProp#1756]
Calling

`PropsSI("H", "T", 325.15, "P", 3800, "INCOMP::LiBr[0]")`

throws an exception on the latest version (6.2.1):

**System.ApplicationException
  HResult=0x80131600
  Message=Initialize failed for backend: "INCOMP", fluid: "" fractions ""; error: key [] was not found in string_to_index_map in JSONIncompressibleLibrary**

On v6.1.0, it returns

`67181.93463102358`

Tested with the C# version on Windows and Darwin 64-bit.

**Comment by henningjp** [comment]
I noticed this as well.  The Mathcad verification sheet tests "INCOMP::MITSW[0]" and it says the fluid string is invalid.  This could be related to the patch we put in for dropping mixture components that have a mole fraction of zero from the mixture calculation under HEOS.  I bet it needs a backend check so that it leaves INCOMP fluid strings alone.  I can peak at it as well.

**Comment by henningjp** [comment]
@DanWBR This will be an easy fix.  In the mean time, using the dash notation still works.  So you can use fluid strings like "INCOMP::LiBr-0%".

**Comment by DanWBR** [comment]
Thanks @henningjp. I'll wait for a fixed version, using v6.1.0 in the meantime.
