### ISSUE TITLE
OSX 10.14 builds

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1782]
As already discussed in 6c46d7d2572223bff4b0772c022fa86ad970846f and #1778, we should find out how we would like to handle the Python builds on newer OSX versions.

I think that the naive approach from e4a0ce6a55c7772f4c25d1cdd853eb8deba5028b, which lets Python handle all the settings is fine. The only problem is that it does not work for newer XCode versions, but we are able to build wheels that also work on the latest OSX installations.

What are your thoughts @ibell ?

**Comment by ibell** [comment]
I agree that we need to come to a consensus about what to do about standard libraries on OSX.  I've been spending hours trying to get my slave box working again and getting all the slaves that should work properly working properly.  I think I'm almost there, the last sticking point is the documentation generation.  Then I'll put this entirely back in your hands, since you've gone deeper down the rabbit hole than I have.

The only conclusion for me is: the standard libraries on OSX are very confusing to get right, and an order of magnitude trickier once Python enters the fray

**Comment by jowr** [comment]
Did you check my RECENT_COMPILERS branch? I have triggered a build there and the docs seem to build fine... 

By the way, I also updated the buildbot config on the server to incorporate your changes.

**Comment by ibell** [comment]
Additional information that was helpful for me, and might be for you too: https://github.com/pandas-dev/pandas/issues/23424

**Comment by ibell** [comment]
Yup, I saw your branch, and if that is all building safely, then I think we can merge it into master

**Comment by ibell** [comment]
Feel free to revert my changes in setup.py if you think that is necessary

**Comment by jowr** [comment]
Thanks - I am afraid that the docs do not build anymore. Are you still running XCode 10?

**Comment by ibell** [comment]
Yeah, I'm working on it right now, fixing some small issues with paths.
The examples run now, and I'll keep at it until the docs build properly

**Comment by ibell** [comment]
Aside from some small issues in the docs (I think we need to build the docs in Python 3 now due to doxylink), all my slaves are 100% operational. The floor is yours for 10.14 now.
