### ISSUE TITLE
Sphinx builder still broken

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#1784]
@ibell , could you have a look at the Sphinx builds?

**Comment by ibell** [comment]
Yeah, I've already tried pretty hard to get this working.  The core issue is that there are bugs in the sphinxcontrib-doxylink package, and the new version, without the bugs, is python 3.x only, and the sphinx builder is currently running python 2.7 because I need python 2.7 to run the buildbot-slave==0.8.14.  One intermediate solution would be a conda environment for the doc building, which would actually potentially be a massive improvement from the standpoint of reproducibility.  I'm going to experiment with that today.

My other thought is to make the doc build happen in a docker container, this would also help a lot with dependency management, which is handled in a very ad hoc way and cost me a lot of hours in the last days doing builds, and then only after realizing that a dependency was missing going to install the dependency and try again.

**Comment by jowr** [comment]
or we use a special TravisCI build or we make a mirror on GitLab and use their CI infrastructure...

**Comment by ibell** [comment]
The "right now" solution is the conda environment, the better solution is
any of those that you propose.  Only issue might be that we need to install
some software to run the examples, but nowadays many CI systems support
docker, which should be fine for our purposes.

**Comment by ibell** [comment]
Almost there.  I have a docker setup nearly complete to generate the docs,
will be very slick, and much easier to maintain than before. Thanks for the
inspiration!

**Comment by ibell** [comment]
The slow incompressible docs were failing to build silently, I made the script fail loudly, but I don't know what to do about #1786, I've done what I can.
