### ISSUE TITLE
New fluids on Coolprop

### ISSUE THREAD

**Issue by Malaik78** [CoolProp/CoolProp#1825]
Hi,

I'm searching to add new fluids and their properties on Coolprop.
I need to work on the R455A, a fluid with an important sliding (10-12°C).

Someone has a solution for that ?

Thanks a lot.

**Comment by Relojuca** [comment]
Hi.

The refrigerant R455A is a mixture of the following components R744/R32/R1234yf  with this mass composition (%) (3.0/21.5/75.5), and as far as I concern, there is no equation of state for this pseudo-fluid, you should try to handle it as mixture in coolprop with the adequate interaction parameters.

Regards

Julián

PS. I think that you should close the issue, because it is not a malfunction of CoolProp.

**Comment by Malaik78** [comment]
Thank you for your answer. 
I close the issue.

Best regards.
