### ISSUE TITLE
CoolProp o Python error???

### ISSUE THREAD

**Issue by alexansaa** [CoolProp/CoolProp#1895]
### Description

I'm triyng to study R1234ZE(E) refrigeration cicles with CoolProps in Matlab. At the moment, I have written code for getting values for S, H and U (values that i might use) for a specified Temperature vector ranging from Tmin to Tmax (m number of elements) and for a specified matrix (n,m) of presures maped from a normaliced function p=f(p_sat, p_norm) as matlab propose in their web pages. I have succeded in this attempt. The problem appears when I try to get a more fine mesh (i.e.: n=1000, m=1200), and Matlab shows me:

Error using CoolProp/CoolProp.__Props_err2
(CoolProp\CoolProp.cpp:45002) (line 314)
Python Error: ValueError: Residual function in secant
returned invalid number :
PropsSI("S","P",3634769.515,"T",187.2950169,"R1234ZE(E)")

Error in CoolProp/CoolProp.PropsSI
(CoolProp\CoolProp.cpp:46859) (line 427)

Error in CoolProp/CoolProp.PropsSI
(CoolProp\CoolProp.cpp:47071) (line 347)

As you can see, P is near P_crit, but T is far away from T_crit..

I need some fine mesh to check my results correctly. Maybe you can help me solving this problem. Also, I have read that the problem was issued in 2015, but that error was in critical region.. I dont think im having this problem in critical region, but in subcooled liquid region.

P.S.: sorry for my bad english and thank you in advance for your help and time.

### Versions

**CoolProp Version:** [6.2]
**Operating System and Version:** [W10]  
**Access Method:** [Matlab R2019a with PropsSI, via python 3.6]  

### Additional Information
![Captura](https://user-images.githubusercontent.com/60579598/73612675-c1bfe100-45bb-11ea-84ab-b50fb96cb2fd.PNG)

**Comment by Relojuca** [comment]
Hi 

I think that is a problem of the solver of CoolProp in this point, I tried to perform the calculation in Python and returns the same issue, however, if you know the phase of your state, you could help to  CoolProp to perform the calculation through the phase specification tool, as shown in the following line command:

PropsSI("S","P|liquid",3634769.515,"T",187.2950169,"R1234ZE(E)")

Check the documentation:

http://coolprop.org/coolprop/HighLevelAPI.html#imposing-the-phase-optional

Regards

Julián


De: alexansaa
Enviado:domingo, 2 de febrero de 2020 3:06 p. m.
Para: CoolProp/CoolProp
Cc:Subscribed
Assunto: [CoolProp/CoolProp] CoolProp o Python error??? (#1895)

Description
I'm triyng to study R1234ZE(E) refrigeration cicles with CoolProps in Matlab. At the moment, I have written code for getting values for S, H and U (values that i might use) for a specified Temperature vector ranging from Tmin to Tmax (m number of elements) and for a specified matrix (n,m) of presures maped from a normaliced function p=f(p_sat, p_norm) as matlab propose in their web pages. I have succeded in this attempt. The problem appears when I try to get a more fine mesh (i.e.: n=1000, m=1200), and Matlab shows me:
Error using CoolProp/CoolProp.__Props_err2
(CoolProp\CoolProp.cpp:45002) (line 314)
Python Error: ValueError: Residual function in secant
returned invalid number :
PropsSI("S","P",3634769.515,"T",187.2950169,"R1234ZE(E)")
Error in CoolProp/CoolProp.PropsSI
(CoolProp\CoolProp.cpp:46859) (line 427)
Error in CoolProp/CoolProp.PropsSI
(CoolProp\CoolProp.cpp:47071) (line 347)
As you can see, P is near P_crit, but T is far away from T_crit..
I need some fine mesh to check my results correctly. Maybe you can help me solving this problem. Also, I have read that the problem was issued in 2015, but that error was in critical region.. I dont think im having this problem in critical region, but in subcooled liquid region.
P.S.: sorry for my bad english and thank you in advance for your help and time.
Versions
CoolProp Version: [6.2]
Operating System and Version: [W10]
Access Method: [Matlab R2019a with PropsSI, via python 3.6]
Additional Information

**Comment by ibell** [comment]
Have you tried to use the tabular interpolation in CoolProp already:
http://www.coolprop.org/coolprop/Tabular.html ?  You'll likely want to use
a more computationally capable language than MATLAB (e.g., Python or C++)
if you really care about speed to avoid the MATLAB->Python calling
interface.

**Comment by alexansaa** [comment]
Dear all,

Thank you for the advise. In deed Relojuca's way was very useful. But also im trying Python from now on.
Also I stop pushing return from PropsSI at high fine mesh, and correct the issue by using a secondary funtion that map a finer localized mesh around the value the user is supposed to look for.

Again, Im very sorry form my bad English.

Thanks all!!

**Comment by ibell** [comment]
Indeed, this would have been my recommendation as well; patch the holes with the data around it.  You can also do the p,h calls yourself if you have a T,rho state point very close to your desired state point.  Probably we could fix this in the tabular interpolation building routines too.
