### ISSUE TITLE
Glycol antifreeze forumulations not found in documentation

### ISSUE THREAD

**Issue by j-c-cook** [CoolProp/CoolProp#1924]
### Description

I am interested in the following mixtures, which are not available:
- Propylene Glycol / Water 
- Ethylene Glycol / Water 

The individual fluids water, ethanol and methanol are all documented and can be used in CoolProp. However, I see no mention of propylene glycol and ethylene glycol. 

While individually propylene and ethylene are available, the chemical formulas are not the same as the glycol mixtures. 

How should I go about implementing propylene glycol and ethylene glycol into CoolProp?

**Comment by Werkeng** [comment]
You can find this example:

# Specific heat (J/kg/K) of 20% ethylene glycol as a function of TIn
[54]: PropsSI('C','T',298.15,'P',101325,'INCOMP::MEG-20%')Out[54]:
3905.2706242925874

...here: www.coolprop.org/coolprop/HighLevelAPI.html
For "Propylene Glycol / Water" use "MPG" instead of "MEG".
Hope it helps.

Best regards,
Sergej Nishpal.

пт, 24 апр. 2020 г., 21:53 Jack C. Cook <notifications@github.com>:

**Comment by j-c-cook** [comment]
That does help, thank you. 

Is there a place that mentions "MPG" == Propylene Glycol / Water in the docs?

**Comment by ibell** [comment]
I fixed the docs, and they are currently only up to date on the upstream
build server:
http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/fluid_properties/Incompressibles.html#pure

**Comment by j-c-cook** [comment]
Okay thank you. The combination of the <a href="http://www.coolprop.org/coolprop/HighLevelAPI.html">example</a> and the documentation on <a href="http://www.coolprop.dreamhosters.com:8010/binaries/sphinx/fluid_properties/Incompressibles.html#pure">The Different Fluids</a> answers my questions. 

Specifically this example provided by @Werkeng 
```
# Specific heat (J/kg/K) of 20% ethylene glycol as a function of TIn
[54]: PropsSI('C','T',298.15,'P',101325,'INCOMP::MEG-20%')
Out[54]: 3905.2706242925874
```
