### ISSUE TITLE
Suggestion for CoolProp/REFPROP PATH issues documentation

### ISSUE THREAD

**Issue by krestenks** [CoolProp/CoolProp#1964]
Please add a description of the RPprefix environment variable to http://www.coolprop.org/coolprop/REFPROP.html#path-issues

We just spent a day figuring out that there was more to moving REFPROP than just changing the PATH variable as described in the documentation. I seems that RPprefix even overrides ALTERNATIVE_REFPROP_PATH.

You could add the following:
"On windows the RPprefix environment variable is used to locate the fluids directory, and therefore this must be set to the ."

CoolProp 6.4.1
python 3.6
REFPROP 10
Windows 10

Best regards
Kresten

**Comment by ibell** [comment]
Nowhere in CoolProp is the RPPREFIX environment variable used directly, but you are right, you should also update RPPREFIX if you move REFPROP. For that reason I always set the path to REFPROP with ALTERNATIVE_REFPROP_PATH.  That should always win, because it provides the absolute path to each fluid file. If that is not the case, it's a bug (with REFPROP), and we'd appreciate a report.

**Comment by krestenks** [comment]
It seems that ALTERNATIVE_REFPROP_PATH wins for mixtures but not for fluids. I will report it on the REFPROP github.
