### ISSUE TITLE
Coolprop extension on Windows for Excel AND LibreOffice

### ISSUE THREAD

**Issue by jrd10** [CoolProp/CoolProp#2155]
Hello, thank you for CoolProp

Sorry for this very weird question.

### Prerequisites
We have CoolProp working on Windows with Excel.
We add LibreOffice on the same PC and its macros works fine.

We would like to have CoolProp for LibreOffice too :).

### Description

CoolProp does not work in LibreOffice : Err 504 instead of Water :)

### What I have done

I have used the same extension "CoolProp_sources.zip" than this one for Windows (as I have understood, it is a multiplatform extension). Do you think, there is a conflict? 

**Do we have to upload a new copy of this file in a separate repertory and add this extension from this second file?**

Thank you for your feedback.

Please, confirm that The "LibreOffice Wrapper" is the same thing that "LibreOffice Extension". 
Not need to upload an extension + a wrapper files?

Thank you again for coolProp. José from France.

_Note: I have already installed CoolProp on Ubuntu for LibreOffice :). Thank you again for your help (@spinnau and all the team)
I tried the CoolProp.oxt extension, it does not work... on Windows! Normal!_

**Comment by spinnau** [comment]
The CoolProp.oxt extension for LibreOffice works on Linux, Windows and macOS by invoking the Python CoolProp package in the background. On Windows, LibreOffice comes with its own bundled Python. The CoolProp Python package can be installed directly from the settings menu of the extension, as described at http://coolprop.org/coolprop/wrappers/LibreOffice/index.html#installation in step 5.

**Comment by jrd10** [comment]
Thank you for your time @spinnau 
Please note I have read all your document and all issues connected with LibreOffice.
_Sorry for request all this precision. In fact, it is not my PC and I do that remotely._

I did (several times) step 5 :) after the extension installation.
And it does not work for LibreOffice. Err 504.

The question was, is it possible to have, on the same Windows PC, Coolprop in Excel (which currently works) AND in LibreOffice (which currently does not work)? 
Could we use the same ext. file (conflict) or do we have to duplicate it for LibreOffice?

If Yes, I could try to install Python with: `sudo pip3 install coolprop`

Thank you again for your time. José

**Comment by spinnau** [comment]
It is possible to install CoolProp for Excel and LibreOffice on the same Windows PC. But the Excel Add-in and the LibreOffice Extension are completely different and you need to install both of them.

The Excel Add-in uses DLL-files containing the compiled CoolProp library. The LibreOffice extension makes use of CoolProp by invoking Python and thus allows for easy multiplatform-support, as the CoolProp Python package is already available for different operating systems and hardware platforms.

Have you tried the latest version of the LibreOffice Extension? In #1993 the extension was changed to use pip for downloading the Python package. Before the were problems for some Python versions and platforms. Since this change there was no new release. For convenience I have added the latest build of the Extension and the test file here:

[CoolProp.oxt.zip](https://github.com/CoolProp/CoolProp/files/9349231/CoolProp.oxt.zip) (rename file to CoolProp.oxt)
[TestLibreOffice.ods](https://github.com/CoolProp/CoolProp/files/9349234/TestLibreOffice.ods)

Can you please uninstall the extension and try again with the files above according to this guide http://coolprop.org/coolprop/wrappers/LibreOffice/index.html#installation?

**Comment by jrd10** [comment]
Hello @spinnau Thank you for this feedback.

I sent to the user these instructions.
Feedback not later than Friday :).

I would like to mention that, with LibreOffice, we have often some error message screens : <class 'Attribute Error'>...
I click on OK and LO works :)

See you soon. José

**Comment by jrd10** [comment]
Hello @spinnau 

It works :)
Thanks for your help.

Have a good weekend. 

José from France.
