### ISSUE TITLE
manual install files not showing up on soundforge

### ISSUE THREAD

**Issue by ceichrod** [CoolProp/CoolProp#2260]
There are several files missing from the 6.4.3 manual install files on soundforge. 

shared_library/Windows32bit_stdcall 
xla, xlam, and TestExcel.xlsx from MicrosoftExcel 

Getting the error message The "/CoolProp/6.4.3/shar..ndows/32bit__stdcall" file could not be found or is not available. Please select another file.

**Comment by pkirkham** [comment]
Yes, there are many files that no longer are appearing on Sourceforge with the latest releases. It also appears that there are many other pre-compiled wrappers etc. that disappeared between 6.4.1 and 6.4.2. My resolution for the issue was to clone the respository using git, install a compiler (ended up with both MinGW and Visual Studio 2022), install all the other tools needed (cmake, SWIG, command line git, 7zip) and then try to build and compile myself. Whilst I've done lots of work in Java before, I'd never really had a need to delve into the world of C++, but I was able to get it working.

My point is that if you really **need** the manual install files, you should be able to generate the 32-bit wrapper yourself following the instructions at [http://www.coolprop.org/coolprop/wrappers/Excel/index.html#user-compiled-binaries](http://www.coolprop.org/coolprop/wrappers/Excel/index.html#user-compiled-binaries). The Excel add-ins are probably identical between CoolProp releases, so you can use the older ones from 6.4.1. Also, I believe the automatic installer is working for 6.4.3 as I've also used that on my system successfully.

**Comment by ibell** [comment]
Yes, we need some core developers to step up and get their hands dirty in
the land of github actions. It is a lot of (thankless) work to manage the
continuous integration.

**Comment by jowr** [comment]
Yes, we have removed a lot of files from the automatic builds to keep the maintenance efforts low. @ceichrod , why could you not use the installer? We made it especially for Windows and it is still part of the released binaries.

**Comment by jowr** [comment]
The next nightly release should contain all different flavours of shared libraries as per 43f1e96
