### ISSUE TITLE
R-134a Saturation Properties Are Severely Incorrect

### ISSUE THREAD

**Issue by jkg1993** [CoolProp/CoolProp#2425]
## Description

When using CoolProp 6.6.0 the values returned for the enthalpy, internal energy, and entropy of R-134a are grossly incorrect. I first noticed this when using the PropsSI function in a Jupyter Notebook, but this problem is also present in the web application for saturation properties of R-134a.

## Steps to Reproduce On CoolPropGit
Starting at the webpage: https://ibell.pythonanywhere.com/

### 1. Change the fluid to R-134a
From here you can just input saturation properties and compare to accepted values, you will see that they are incorrect. I'll give some specific examples below.

### 2. Set the values as below: (Note this is not code, just what you need to enter on the webpage.)
    Input 1: P_Sat = 60000 Pa

### 3. Set the values as below: (Note this is not code, just what you need to enter on the webpage.)
    Input 1: P_Sat = 60000 Pa
    Input 2: Vapor Quality = 0
    Output units should be set to, "Mass-based"
    Click submit
    Input 2: Vapor Quality = 0
    Output units should be set to, "Mass-based"
    Click submit

### 4. Correct vs Returned Values: (Note all values should correspond to a saturated liquid)
    Value            Correct                    Returned
    Temp            ~236.2 K                  236.2 K
    Density         ~1409 kg/m^3        1408.8 kg/m^3
    Enthalpy       ~3841 J/kg               152001 J/kg
    Entropy         ~16.34 J/kg/K          812 J/kg/K

### 1. Run the following Python Code

`from CoolProp.CoolProp import PropsSI
df = PropsSI('D', 'P', 60*1000, 'Q', 0, 'R134a'); #SatLiq Density
uf = PropsSI('U', 'P', 60*1000, 'Q', 0, 'R134a'); #SatLiq Internal Energy
hf = PropsSI('H', 'P', 60*1000, 'Q', 0, 'R134a'); #SatLiq Enthalpy
sf = PropsSI('S', 'P', 60*1000, 'Q', 0, 'R134a'); #SatLiq Entropy
Tsat = PropsSI('T', 'P', 60*1000, 'Q', 0, 'R134a'); #SatTemp
print(f'Saturation Temp = {Tsat} [K]')
print(f'Liquid Density = {df} [kg/m^3]')
print(f'Liquid Internal Energy = {uf} [J/kg]')
print(f'Liquid Enthalpy = {hf} [J/kg]')
print(f'Liquid Entropy = {sf} [J/kg/K]')`

### Actual Results

Saturation Temp = 236.21539849905753 [K]
Liquid Density = 1408.801084369011 [kg/m^3]
Liquid Internal Energy = 151958.88094147237 [J/kg]
Liquid Enthalpy = 152001.47034651015 [J/kg]
Liquid Entropy = 812.0209114819199 [J/kg/K]

### Correct Results

Saturation Temp = 236.2 [K]
Liquid Density = 1408.8 [kg/m^3]
Liquid Internal Energy = 3798 [J/kg]
Liquid Enthalpy = 3841 [J/kg]
Liquid Entropy = 16.34 [J/kg/K]

## Final Comments
Looking at Enthalpy specifically, the answer above is off by a factor of nearly 40. However, when the saturation pressure is raised the error goes down in a regular way. At around 4000 kPa the ratio: returned/correct drops to about 1.5 or 2.

You'll notice using the python implementation that the values for temperature and density are correct, but the rest are still just as wrong. In anycase I'm hopeful that this can be resolved quickly.

## Versions

**CoolProp Version:** [6.6.0]  
**Operating System and Version:** [Windows 11 Home, Version 23H2]  
**Access Method:** [Python 3.12.2 via Jupyter Notebook]
### Jupyter Versions
jupyter                   1.1.1
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_proxy      4.4.0
jupyter_server_terminals  0.5.3
jupyterlab                4.2.5
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_vpython        3.1.8
jupyterlab_widgets        3.0.13

**Comment by ibell** [comment]
Please see the most popular FAQ by a mile: https://github.com/CoolProp/CoolProp/blob/master/FAQ.md (first FAQ)

**Comment by jkg1993** [comment]
@ibell 
Why was this closed? The FAQ is regarding small deviances from accepted values, these deviances are not small. There is a mistake in the CoolProp library for R-134a, it's referencing the wrong refrigerant for enthalpy, entropy, and internal energy.

This needs to be corrected. Your FAQ absolutely does not address the issue that I raised.

**Comment by wandadars** [comment]
@jkg1993  To make sure we're looking at the same thing. You are saying that if you have a gaseous state specified like TPX_1 and TPX_2, that the H_2 - H_1 does not agree with other sources? Where H is the enthalpy in this example. From your example it looks like the temperature and density are close to the "correct" values. The absolute values of the enthalpy, internal energy, and entropy are essentially arbitrary (given the choice of a reference state).

**Comment by jkg1993** [comment]
@wandadars 
What I mentioned above is not a gaseous state, in this case the fluid is saturated. The Q term indicates vapor quality, 0 is a fully liquid saturated mixture while 1 is a fully vapor saturated mixture.

When using PropsSI H is the mass-based specific enthalpy, and it is given in J/kg by CoolProp.

Now CoolProp does give the correct saturation temperature & liquid density at the specified state. But the values provided for enthalpy, internal energy, and entropy are completely wrong. Not in an arbitrary way where the differences in enthalpy are still correct. If you used these values to calculate the heat transfer between different points in a vapor cycle, then you would get horribly incorrect values.

I will say, that other refrigerants that I have tested do not exhibit this problem. I believe that CoolProp is referencing the enthalpy, internal energy, and entropy values for a different refrigerant by mistake. This needs to be fixed.

**Comment by ibell** [comment]
@jkg1993 There is nothing wrong with R-134a enthalpies. I can say this with confidence because they agree with the ones in REFPROP to plenty of significant digits:

```python
import CoolProp.CoolProp as CP 
fluid = 'R134a'
for backend in ['HEOS','REFPROP']:
    print(CP.PropsSI('Hmolar', 'T', 300, 'Q', 0, backend+'::'+fluid))
```
yielding
```
24200.886823043602
24200.882950915384
```

What is wrong is that you don't understand how reference states work. Absolute values of enthalpy should only be compared between two sources if you are 100% sure that both are using the same reference state. Otherwise there can be a constant offset (in an additive sense) between the two sources. CoolProp tries to match the reference state used in REFPROP and so will in most cases match REFPROP values by default.

If you were to calculate the difference in enthalpy between saturated liquid and vapor values at a given temperature you would find that their difference is the same; that is what @wandadars was getting at and what the FAQ is getting at.

Please be mindful of your tone. CoolProp is a volunteer maintained and run project and as such we don't owe you anything.

**Comment by jkg1993** [comment]
@ibell I'm not sure where my tone went wrong, but I do apologize for any offense. Perhaps I am looking at this wrong, but from my perspective these values do not align with text book references that I have or any university data that I can find. I'm also getting different calculations for evaporator cooling from CoolProp than when I reference tables published by a university. I'll explain what I can below.

I can see above that your values agree with what the REFPROP database is giving you, but both of those values disagree with what is published by universities. Have a look at [Cambridge University Press & Assessment](https://www.cambridge.org/us/files/2313/6697/5548/Appendix_C.pdf) or at [Michigan State University](https://www.egr.msu.edu/classes/me417/somerton/R134a%20Tables.pdf) and compare a few saturation states to their tables. You will see a large disagreement.

I also wanted to note that I was using mass based enthalpy values, and your comment above uses the molar based masses. I'll do some comparisons with the MSU table and CoolProp below, but they will be mass based values.

## MSU Table Values 26 degC & 60 degC
I'm going to take some differences to show you what I was describing above, and below I will just fill in the MSU temperature table for two temperatures. I'm changing the enthalpy units to J/kg since that is the CoolProp default.

| Temp [degC] | Psat [MPa] | Sat Liq Enthalpy h_f [J/kg] | Sat Vap Enthalpy h_g [J/kg] |
| --- | --- | --- | --- |
| 26 | 0.68530 | 85750 | 261480 |
| 60 | 1.6813 | 137420 | 275990 |

### CoolProp Enthalpies at 26 degC
```
import CoolProp.CoolProp as CP
fluid = 'HEOS::R134a'
qual_list = [0, 1]
for qual in qual_list:
    print(CP.PropsSI('Hmass', 'T', 26+273.15, 'Q', qual, fluid))
```
Which gives the following in J/kg
```
235972.9441638312
412839.3475852961
```
#### Comparing with MSU Table @26 degC
| Enthalpy Type | MSU Value [J/kg] | CoolProp Value [J/kg] | % Diff from MSU |
| --- | --- | --- | --- |
| Liquid | 85750 | 235973 | 175 % |
| Vapor | 261480 | 412839 | 57.9 % |

I don't have the time at the moment to finish this analysis, but I will try to get on later and either edit this comment. Please have a look at let me know your thoughts.

**Comment by wandadars** [comment]
@jkg1993  I want to be clear here to make sure we're on the same page. When we say "between two states", we mean within the same framework (that is CoolProp or the MSU textbook), if you take the difference between enthalpies at two states, _that_ difference is what you should compare to other sources. 

In your example, at 26 degrees Celsius, the difference between the liquid and vapor states in Coolprop is:  176866 J/kg. The difference between those same two states in the MSU textbook is:  175730 J/kg.  This difference between these two values is 0.646 %, which is pretty good.

Enthalpy is a measure of the heat content of a system, but when we look at tables or charts in textbooks, we need to understand that these values are based on a specific reference state. The idea of a reference state is similar to choosing a starting point or baseline, from which we measure everything else.

Think of it like using sea level as the reference height when we talk about how high a mountain is. If one book decides that sea level is at a different height than another book, then the height of the same mountain will appear different in each book. The mountain hasn’t changed—only the reference point.

For enthalpy, textbooks typically use a reference state where the enthalpy of a substance (such as water, oxygen, or nitrogen) is defined as zero at a certain temperature and pressure (often 25°C and 1 atm, for example). However, this reference state can change depending on the system or situation being studied. If another book or source uses a different reference state, the enthalpy values for the same substance at the same conditions may appear different because they're being measured from different "zero points."

The key thing to remember is that the difference in enthalpy between two states (like initial and final conditions in a process) is what matters in calculations. As long as the same reference state is used consistently, the changes in enthalpy will be the same, even if the absolute values look different. So, if the values in your textbook don’t match values in CoolProp, it's likely due to different choices of reference states.  


Here's another [reference ](http://www.coolprop.org/coolprop/HighLevelAPI.html#reference-states)for the concept.

**Comment by longemen3000** [comment]
just to add to the conversation, MSU tables use the ASHRAE reference state (H = S = 0 at -40°C saturated liquid). according to the original R134a paper, the reference equation of state uses the IIR reference point (H = 200.0 kJ/kg, S=1.0 kJ/kg/K at 0°C saturated liquid).

**Comment by ibell** [comment]
It all comes down to reference states. The notes from @wandadars and @longemen3000 provide more context. 

In future, it is better to start your message off like "why do I get such different enthalpies" rather than "your enthalpies are wrong".

**Comment by jkg1993** [comment]
@ianhbell I reread my initial post and took a look at everything again, and I wanted to apologize. I did write my post with a very accusatory tone, and I should have phrased it more like a question. You were correct initially, and I didn't understand reference states.

Thank you to @wandadars for their comment. After looking at what you said everything started to make sense for me. 

I edited the post above to give it a less accusatory tone, but I wanted to leave it up incase anyone else came along who happened to me almost as ignorant and stupid as me. Hopefully it helps avoid more mindless posts from people like me.

**Comment by ibell** [comment]
@jkg1993 Thank you for your response. I knew immediately from your question what the issue was, having fielded variations on this question many, many times.

I'm fine with your solution, and thank you for taking the time to re-consider your communication approach. No hard feelings, just an opportunity for growth.
