### ISSUE TITLE
Re-implement tabular methods

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#262]
TTSE generation
Bicubic generation

**Comment by ibell** [comment]
Much progress in https://github.com/CoolProp/CoolProp/tree/tabular

**Comment by ibell** [comment]
@jowr, what do you think about using linear interpolation for the transport properties?  In that case we could just integrate them in the "normal" way into the h-log(p) and T-log(p) tables.  The accuracy of the underlying transport correlations tends to not be so super good anyway.

**Comment by jowr** [comment]
I agree, the predictive methods do not provide data that justify a huge effort.

**Comment by ibell** [comment]
@jowr, @squoilin : 
T(h,p) is approximately 1000 times faster with TTSE than the EOS for n-Propane at h= 3 J/mol, p = 2e6 Pa.  So its starting to look quite good, and I think this is quite a bit faster than before as well!

Some caveats:
* Not yet checking for two-phase curves, that will add a bit of time, perhaps double it, but I'll see what I can do
* Not yet finding the *nearest* node, just using the "left" node in the cell that bounds the state point.

**Comment by ibell** [comment]
Right now, unless my timing has been too aggressively optimized away, in C++, it is 111 us/call using the EOS, and 0.061 us/call using TTSE.

**Comment by ibell** [comment]
I think this figure is starting to look familiar, eh @jowr & @squoilin : 
![ttse_bicubic](https://cloud.githubusercontent.com/assets/1859947/6322662/90f5300e-bad6-11e4-8b81-19c8e5b68704.png)

**Comment by ibell** [comment]
Looks like we are still at less than 0.1 us per call for single-phase p,h inputs which isn't bad at all.

It seems that the evaluation of hmax for the table needs to be improved.  It goes up to Tmax, but clearly it is still missing the right part of the table.

**Comment by jowr** [comment]
One of the challenges is that h_max is not constant. Evaluating h as a function of T gives you, of course, something that follows an isotherm. Hence, it goues straight at low pressures, but bends to the left above the critical point and turns back to the right afterwards until it meets the melting line. So why not have h_max as a function of p? The shape with only two inflection points suggests that 3rd order polynomial function might be sufficient.

**Comment by LeonardoPierobon** [comment]
Hi all,

I met an unexpected problem with TTSE in Modelica for calculating the dynamic viscosity of Toluene at 0.46 bar and 70 degC (liquid phase). For a grid resolution for the tables is 200x200 I get an erroneous value when compared to the case without TTSE or Refprop. The problem is solved using a resolution of 500x500.

Here is a sample of the Modelica code and a link to the risults  

model test_Toluene
  Test.Media.CoolProp.Toluene_TTSE.ThermodynamicState state_TTSE;
  Test.Media.CoolProp.Toluene.ThermodynamicState state_CoolProp;
  Test.Media.RefProp.Toluene.ThermodynamicState state_RefProp;

equation 
    state_TTSE = Test.Media.CoolProp.Toluene_TTSE.setState_pTX(0.46e5,343.15);
    state_CoolProp = Test.Media.CoolProp.Toluene.setState_pTX(0.46e5,343.15);
    state_RefProp = Test.Media.RefProp.Toluene.setState_pTX(0.46e5,343.15);

end test_Toluene;

![screenshot 2015-02-19 08 45 14](https://cloud.githubusercontent.com/assets/9587555/6327776/1ed5e04c-bb60-11e4-8f92-6f0021b9ec14.png)

Leonardo
