### ISSUE TITLE
Modelica/ExternalMedia re-integration

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#263]

**Comment by ibell** [comment]
@squoilin @adesideri @jowr You can start thinking about this in earnest now, most of the bits and pieces are ready, except for the TTSE and bicubic which are almost there.

**Comment by jowr** [comment]
:+1: for a coolpropsolver.cpp in ExternalMedia that uses the state class ...

**Comment by squoilin** [comment]
@jowr isn't it what we were doing in version 4.2 already?

**Comment by jowr** [comment]
Yes, I meant the **Abstract**State class.

**Comment by ibell** [comment]
Oh boy, looks like @jowr made a lot of improvements to the solver, looks like I might let him work on this since I don't follow all the new machinery that was added

**Comment by jowr** [comment]
When do you want to release 5.1? I have some time in May to do this.

**Comment by ibell** [comment]
I could do it, but the issue is that I don't have access to Modelica, which
makes it a bit complicated.  I guess for now I'll remove the milestone and
we'll see how it goes.  I don't think it would be much work

**Comment by jowr** [comment]
I am gong to do this soon. One thing we should discuss here is how to handle two-phase properties. Should the changes made to implement https://github.com/ibell/coolprop/issues/25 be included in the Modelica wrapper or is this EXTTP switch something that we should have on a global level?

**Comment by ibell** [comment]
I would rather that all the EXTTP stuff stays in the Modelica wrapper I
think.  It is not physically consistent behavior, and for that reason would
be better suited to the Modelica interface I think.

**Comment by squoilin** [comment]
If this can wait one more month, @JonWel will start working on that around mid-june.

**Comment by ibell** [comment]
I'm not in any rush at all since I don't use ExternalMedia.  @jowr and
@JonWel should coordinate their efforts.

**Comment by JonWel** [comment]
I'm currently working on the re integration.

As for the EXTTP, I see nothing to link to in CoolProp 5.
Do I temporary display a warning until it is include in the Modelica wrapper? Do I add it myself from the code in CoolProp 4?

In CoolPropSolver::setFluidConstants(), there is a TODO:
``` C++
/* TODO: Fix this dirty, dirty workaround */
if (_fluidConstants.MM > 1.0) _fluidConstants.MM *= 1e-3;
```
Does this workaround still necessary?

In this same CoolPropSolver::setFluidConstants(), the PropsSI function is used to take the value of theses constants. Wouldn't it be more efficient to use the state class (that has been created before the call to this function) to retrieve theses values more quickly? They are all with P and T = 0, thus requiring only one state update.

Again in the CoolPropSolver::setFluidConstants(), why does the molar mass set to NaN ? (I understand for the critical values but the molar mass still exist).

**Comment by ibell** [comment]
Please discuss with @jowr - I gather he is also working on this

**Comment by jowr** [comment]
HI, it is really good to hear that someone is working on this as I do not have all the time I wish I had. There are a couple of immediate questions that come to my mind. 

  - How do you manage your code? I started drafting something at https://svn.modelica.org/projects/ExternalMediaLibrary/branches/coolprop5 , but you probably do not have write access to that repository. I suggest that we the branch of the SVN here on GitHub and start working collaboratively. 

  - `EXTTP` is not going to be part of the CoolProp core any longer. It was only used in the Modelica wrapper and that is where it belongs. It , however, is important for the Modelica world since it provides interpolations in the two-phase domain that match those used in the standard library. Yes, please implement that!

  - How about mixtures? Some time ago I worked on an extended two-phase package for Modelica at https://github.com/jowr/REFPROP2Modelica . It works, but I never really had the time to integrate it with ExternalMedia. 

  - Instance handling: My initial code contains a wrapper that handles a library of state instances because of the expensive reading and unzipping operations required to initialise the tabular state objects. This code has recently become obsolete because the tabular states now manage pointers to the data tables themselves. We have to make sure the using many different fluids does not lead to an excessive RAM consumption. 

  - Regarding your questions:
     - The TODO should not be valid any longer. It was a fix I made to account for the molar mass not being in SI units, but in g/mol. 
     - Yes, you should use the state class. I have written some code already that I can share with you. In some cases the interpolated states threw errors for constant properties and thus the detour via PropsSI.

**Comment by JonWel** [comment]
* Until now, I only done local modifications, having a place to work collaboratively would surly be better.

* Adding `EXTTP` `C++` code to `ExternalMedia` on the TODO list.

* Adding mixtures on the enhancement list.

* How is this library called?

**Comment by jowr** [comment]
Which library? https://github.com/jowr/REFPROP2Modelica ?

**Comment by JonWel** [comment]
The one for the instance handling that is obsolete due to the new way to handle tables.

**Comment by JonWel** [comment]
* `CoolProp`'s `isTwoPhase()` function is protected, is there a similar function I can use to replace the old `TwoPhase` property of `CoolProp 4`?

* When saturation properties are calculated, for two phase fluids, some values are asked specifically for the Liquid or the Vapour phase (`sV`, `sL` ... but also parameters for density or enthalpy) . Where can I find some `CoolProp 5` equivalents?

**Comment by jowr** [comment]
Let us continue the discussion here: https://github.com/CoolProp/ExternalMedia
