### ISSUE TITLE
Transport Properties on Pure Fluids

### ISSUE THREAD

**Issue by paarfi** [CoolProp/CoolProp#415]
Transport properties are missing for some of the pure fluids. Could you please add?

R41 - Viscosity and ThermalConductivity
R50 (methane) - Viscosity and ThermalConductivity
R113 - Viscosity and ThermalConductivity
R114 - Viscosity and ThermalConductivity
R161 - Viscosity and ThermalConductivity
R365mfc - Viscosity, ThermalConductivity, and SurfaceTension
R720 (neon) - Viscosity and ThermalConductivity
R1150 (ethylene) - Viscosity and ThermalConductivity
R1233zd - Viscosity, ThermalConductivity, and SurfaceTension
R1234yf - Viscosity
R1234ze - Viscosity and ThermalConductivity

**Comment by jowr** [comment]
Thank you for reporting this, could you provide links to the relevant publications?

**Comment by paarfi** [comment]
Well, I could point you to what Refprop is doing. It supports all of these calculations. For example, for ethylene it uses viscosity and conductivity models from this paper (if I understand the Refprop data file format correctly):
Holland, P.M., Eaton, B.E., and Hanley, H.J.M., "A Correlation of the Viscosity and Thermal Conductivity Data of Gaseous and Liquid Ethylene,"  J. Phys. Chem. Ref. Data, 12(4):917-932, 1983.

I don't know if y'all didn't implement these yet because you just missed them, or the equations Refprop is using required a lot more programming and you haven't had time yet, or you weren't happy with the way Refprop was doing it and you wanted to do something better, or maybe some other reason. But these would be nice to have working, especially methane, ethylene, R1234yf, and R1234ze.

**Comment by ibell** [comment]
For ethylene, that paper is a mess, and not easy to implement, which is why
I haven't.  For methane, its mostly an oversight.  For the HFO (R1234yf,
R1233zd, etc.), there aren't transport properties in the published
literature.  As Jorrit said, if you can provide literature sources for the
papers (and ideally the PDF of the paper themselves), we might be able to
help you. A typical transport routine, if there are no issues (and there
often are), takes an hour or two to implement and test.

You can see here where we have gaps in the transport properties:
http://www.coolprop.org/fluid_properties/PurePseudoPure.html#list-of-fluids

For some fluids, REFPROP uses extended corresponding states, and the
correction polynomials (required) are not in the public domain, and
therefore we cannot use them.  That is the case for a lot of fluids.

In general, the transport property experimental data situation is not as
good as it is for PVT data, which is why the transport properties lag the
thermo eos.

**Comment by paarfi** [comment]
Ah, I understand. I am not going to be aware of any literature for this that you are not already aware of. I can fall back on Refprop for those fluids. I'm just looking forward to the day when I can do everything I need in CoolProp. Thanks very much for all your hard work.

**Comment by ibell** [comment]
I'm sorry, but I am going to close this issue since there isn't anything to be done at the moment, and I'm not even sure it is worth keeping it around for the wishlist...
