### ISSUE TITLE
[Tabular] Warn about tabular folder size

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#43]

**Comment by jowr** [comment]
Maybe we should collect all issues in one place -> #262

**Comment by ibell** [comment]
I dunno, I think it is better to keep them as separate issues in general,
it is easier to link commits and issues if they are separate. We could tag
them with [TTSE] or something like that.

**Comment by ibell** [comment]
@jowr - Any thoughts on how best to implement this one?  It's about time.  Looks like it will be pretty easy to use zlib to compress the table files to about 30% of their original sizes, so that will reduce the pressure quite a bit.

That said, it looks like if you build all fluids (p-h and p-T), and its about 20 MB/fluid, you are looking at 2.24 GB, which is quite a lot.  And that's not even considering mixtures.  Perhaps we error out if there are more than 1 GB of tables?  Or something like that?  And add a configuration key that you can set to over-ride this behavior?

**Comment by jowr** [comment]
Sounds reasonable, but would that involve a check of the folder size each time you run CoolProp? We might not be able to get around that... I also noticed that @LeonardoPierobon had quite some issues with the old tables. I hope he shares his experience with us in written form soon... The essence is that we had to increase to matrix size to 300x300 because there were many cases with a faulty evaluation of transport properties. Since most of them were close to the two-phase domain, a robust check for that might as well do the job.

 - Are we sure 200x200 is enough? 
 - zlib sounds like a good idea in any case
 - What about a 2-step procedure? Issue warning at a folder size above 1GB and error out above 1.5GB - both numbers should be configurable. People that want to disable the warnings should just set a high value, no extra key to disable the check.

**Comment by ibell** [comment]
@jowr - I think configuration keys can be used to set the TTSE table size, we just need to be sure that we document this clearly.  Default can stay at 200x200, and we can increase as needed.  Changing the size causes a rebuild of the tables.

For zlib, plan is to use miniz (https://code.google.com/p/miniz/)

Sounds like a plan in terms of warnings/errors.  That is pretty much what I had in mind.  Now just need to figure out how to do cross-platform directory size in c++.  Something like ``du``, but in C++ and that works on windows and linux.  Any ideas?

**Comment by jowr** [comment]
How about this one? http://www.cplusplus.com/forum/beginner/107265/

**Comment by jowr** [comment]
We conclude: Boost or command line call (http://stackoverflow.com/a/15497931)

**Comment by ibell** [comment]
boost = command line = :(

Overall command line is less :( I think.  The dependencies for boost just
to do this are rather large.  What about poco?

**Comment by ibell** [comment]
In the end, two painful recursive solutions, I think linux wins out this time.

**Comment by ibell** [comment]
See #496
