### ISSUE TITLE
Javascript does not work, throws exception on call

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#442]
:(

**Comment by masterull** [comment]
Thanks for the very fast response!

**Comment by jowr** [comment]
Check out the new docs. We now host the javascript files and you simply have to include the from sourceforge: `<script src="http://coolprop.sourceforge.net/jscript/coolprop-latest.js"></script>` instead of `<script src="coolprop.js"></script>`. This way, we can guarantee the library linked there is functional. 

Currently, the link points to version 5.0.3, which is the last one with a working javascript wrapper. @ibell Do you have any idea what went wrong since then? Could it be the `PropsSImulti` function?

**Comment by ibell** [comment]
To be honest I have no idea.  It could be that, but it could be a million
other things too.  Can we bisect any closer to figure out where it broke?

**Comment by ibell** [comment]
I updated the Emscripten SDK, rebuilt a .js, and it works, so I guess we
are in business again.  @jowr and @masterull can you please confirm?

The js should be sitting at www.coolprop.dreamhosters.com:8010/unstable
when they are done

**Comment by ibell** [comment]
And or http://www.coolprop.dreamhosters.com:8010/binaries/, but try
unstable first.

**Comment by masterull** [comment]
Hi Ian, I can confirm that when I use the below included in my webpage it works very well!
<script src="http://coolprop.sourceforge.net/jscript/coolprop-latest.js"></script>

**Comment by jowr** [comment]
OK, I'll update the coolprop-lates.js on sourceforge as soon as we release a new version.

**Comment by ibell** [comment]
Awesome, thanks.
