### ISSUE TITLE
Fix potential buffer overflow with get_parameter_information_string

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#472]
Quote from Mike:

"I looked into get_parameter_information_string() and found that it doesn't check buffer capacity in case of (key < 0), in which case it simply copies error info string to buffer unconditionally. If the buffer happens to be too small, a crash could result. I didn't check other functions receiving buffers."

**Comment by mikekaganski** [comment]
```c++
bool str2buf(const std::string& str, char * buf, int n)
{
  if (str.size() < static_cast<unsigned int>(n)) {
    strcpy(buf, str.c_str());
    return true;
  }
  return false;
}
EXPORT_CODE long CONVENTION get_parameter_information_string(const char *param, char * Output, int n)
{
    int key;
    try{
        key = CoolProp::get_parameter_index(param);
    }
    catch(std::exception &){
        return 0;
    }
    if (key >= 0){
        std::string s = CoolProp::get_parameter_information(key, Output);
        return str2buf(s, Output, n) ? 1 : 0;
    }
    else{
        str2buf(format("parameter is invalid: %s", param), Output, n);
        return 0;
    }
}
```

**Comment by mikekaganski** [comment]
And further, it would be desirable to have a means to get the desired buffer size from DLL function. Now it only reports success or failure.

I see two possibilities: 1. using get_global_param_string() after such unsuccessful call with a dedicated param, even possibly returning an int in the (fixed-size) buffer instead of string:
```c++
...
if (get_parameter_information_string(param, output, n) == 0)
{
  int n1=0;
  get_global_param_string("req_buf_len", reinterpret_cast<char*>(&n1), sizeof(n1));
  output = new char [n1];
  get_parameter_information_string(param, output, n1);
}
...
```

and 2. changing return values of DLL functions from 1(success)/0(failure) to 0(failure)/x(chars in answer) -> if x<n then OK, if x>n then no copy was made, fail.

```c++
...
int n1 = get_parameter_information_string(param, output, n);
if (n1>n)
{
  output = new char [n1];
  n1 = get_parameter_information_string(param, output, n1);
}
...
```

The second way is simpler, faster, but incompatible.

**Comment by ibell** [comment]
I think I prefer and will implement version 1.  In general, I like to avoid API changes unless there is a compelling reason to make the change.  I don't think this reaches that bar.
