### ISSUE TITLE
Add possibility to disable a backend at compile-time

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#507]
Something like what was done in externalmedia to enable or disable solvers

This will help to disable backends that for some reason aren't compatible, like tabular methods on VxWorks.

**Comment by mikekaganski** [comment]
Could you please provide any codepointers to externalmedia?

**Comment by ibell** [comment]
I would say your time is not well spent playing with ExternalMedia - that's
a library for Modelica, and it's a whole different animal

**Comment by mikekaganski** [comment]
Then, could you describe what functionality do you expect from self-registering backends?
Do you suggest that they be dynamic link libraries that, if present in directory, are automatically loaded and used?
Or just a means to simplify adding new AbstractState descendant so that it would be automatically available to methods without need to modify them?

**Comment by ibell** [comment]
Actually, having thought about this some more, the best thing is just to add macros that can be used to disable a backend if we know it is incompatible.  I don't think there is a way to automatically detect all the backends at compile-time.

**Comment by mikekaganski** [comment]
Well, if the abstractstate would contain a static vector member that each descendant would append with its factory, that (factory) would be also static for each backend, then you could have such possibility.
