### ISSUE TITLE
Difference between PropsSI function and  CoolProp.PropsSI function

### ISSUE THREAD

**Issue by daidog** [CoolProp/CoolProp#560]
Hi!
      when I was using CoolProp under MATLAB platform to calculate CoolProp.PropsSI('T','H', 1.036272205127489e+06,'P',  2.248891609586528e+06, 'R410a'), I got an error message as follow:
" Warning: unable to solve 1phase PY flash with Tmin=310.179, Tmax=675 due to error: HSU_P_flash_singlephase_Brent could not find a solution because Hmolar [75218.2 J/mol] is above the maximum value of 62282.006648 J/mol ", but when I changed CoolProp.PropsSI function to PropsSI function, it seems ok, why? Thanks!

**Comment by ibell** [comment]
When you say PropsSI, you mean the function from 4.2.x?  I am 100% sure
that this is just a question of reference state.  Try P,T, P,D and they
should be exactly the same.  See also
https://github.com/CoolProp/CoolProp/blob/master/FAQ.md

In general, you should never use enthalpies to compare libraries,
functions, etc. since you don't know what reference state is being used and
if they are the same.

**Comment by daidog** [comment]
Yes, PropsSI  function is from version 4.2.4. I got it , Thank you!
