### ISSUE TITLE
CoolProp.dll CPU architecture-specific only

### ISSUE THREAD

**Issue by zhivchik11** [CoolProp/CoolProp#582]
Hello,
I have several vb.net projects that are cpu-agnostic (setting "Any Cpu" in visual studio). CoolProp.dll files that come with C# libraries are either 32-bit or 64-bit only. Is there a dll that works on both 32 and 64 bit systems? If not, I would like to try and compile one into a .net managed code (and share if I succeed). Where would i find the source code for the libraries? Has anyone already tried and encountered problems with making a dll that works on both 32 and 64 bit systems?
Thank you!

**Comment by paarfi** [comment]
I don't think that is possible. Your vb.net code can be "any cpu" becuse it gets JIT compiled on the destination machine. CoolProp is a C++ native code library, not managed code, even though they provide a C# wrapper. So their choice of 32bit or 64bit is set at compile time. You can't call a native 64bit dll from 32bit managed code or vice versa. So you are going to need to make explicit 32bit and 64bit compiles of your vb.net code as well, or just use 32bit only since that'll run on 64bit systems too.

**Comment by ibell** [comment]
I think it is also possible to generate two swig modules, one that is
32-bit and one that is 64-bit, and then have a conditional somewhere in
your code to pick up the right one.

Also, 32-bit and 64-bit have different name mangling schemes, which makes
things tricky.  In principle it should be possible though.  You might have
to deliver two dll though

**Comment by zhivchik11** [comment]
paarfi and ibelll, 
Thank you for the replies. Everything you said makes sense. At this point I just took the easy way out and made my current project 32 bit.

**Comment by ibell** [comment]
If you want to dig into it a little bit, here is how it is handled in SMath wrapper: https://github.com/CoolProp/CoolProp/blob/master/wrappers/SMath/coolprop_wrapper/Functions/CoolProp_Phase.cs which is also C# .NET

**Comment by ibell** [comment]
I think for now we are going to close this issue, feel free to re-open if you so desire, and/or can propose a solution
