### ISSUE TITLE
D-P is far slower than it should be

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#751]
See also #411 

```
HEOS
T D 4.40697642479
T P 8.64431444199
P S 51.391382067
P H 59.1938432728
P U 59.8328548544
D P 69.4174248829
T S 109.0744776
D H 114.137972773
H S 1329.19389459
REFPROP
T D 3.30372308009
T P 4.875142208
D P 7.79551870867
D H 46.6686729477
P U 51.4656366013
P H 52.0720486313
T S 61.3970296375
P S 91.1085024762
H S 486.036072611
```

**Comment by thorade** [comment]
You do of course know the Span 2000 book, and I assume you are aware of his suggestion to solve the van der Waals EoS for T to obtain a start value. Without looking at your code/implementation (and just because I like posting links), here is a link to page 52 of the book:
https://books.google.de/books?id=dd410GGw8wUC&pg=PA52

**Comment by ibell** [comment]
Yup, I am aware of that method, I'm not sure why I didn't implement it, its
not too complex, and I think I was just lazy.
