### ISSUE TITLE
The static library is too large

### ISSUE THREAD

**Issue by tianshuluo** [CoolProp/CoolProp#828]
I use the following script to build a static library. The library works fine, but is too large.
```
# Check out the sources for CoolProp
git clone https://github.com/CoolProp/CoolProp --recursive
# Move into the folder you just created
cd CoolProp
# Make a build folder
mkdir -p build && cd build
# Build the makefile using CMake
cmake .. -DCOOLPROP_STATIC_LIBRARY=ON
# Make the static library
cmake --build .
```
My operating system is ubuntu 14.04;  the version of g++ is gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04); the version of cmake is 2.8.12.2.

**Comment by ibell** [comment]
Can you please provide a complete log of your build?

**Comment by ibell** [comment]
Ok, it seems this is something about gcc/g++.  The "solution" is to build a release static library instead of debug (the default), using a different invocation of cmake:

```
cmake .. -DCOOLPROP_STATIC_LIBRARY=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
```
which will give you a release compilation of the static library, but with debug information, though you still can't do step-through debugging.  But its better than nothing.  Or, just get a bigger hard-drive :)
