### ISSUE TITLE
CO2 HEOS does not fail for pressures under Pmin

### ISSUE THREAD

**Issue by Astrinus** [CoolProp/CoolProp#862]
>> CoolProp.Props1SI('PMIN','CO2')
       5.1796e+05
    >> CoolProp.PropsSI('H','T',300,'P',1e5,'CO2')
       5.0743e+05

Version 5.1.1 [MATLAB]

Is this intentional because the values the HEOS provides are still valid?

**Comment by ibell** [comment]
Hmm..  that's a good point.  The point is that 'PMIN' actually refers to the minimum saturation pressure.  We are still trying to decide what to do about p < psat_min since you don't know whether the inputs are gas or solid unless you have a sublimation curve, which we only have for a few fluids unfortunately.  I think what we are doing now is to allow p < psat_min if T > Tt  .  That at least guarantees that the inputs are gaseous and not solid.

**Comment by Astrinus** [comment]
So can I consider values under Pmin affordable?
By the way, are you going to support also solid phase? It may be useful for water and carbon dioxide, I think. If I remember correctly, there was an IAPWS formulation for ice, although I don't think is Helmholtz-based.

**Comment by ibell** [comment]
I'm inclined to add sublimation curves, but they only exist for a few
fluids.  I think I'm going to be looking at this in my day job as well.
Solid EOS exist for very few fluids, CO2 and water being the only ones I am
aware of, though there might be others.  They are obviously the most useful
ones.

**Comment by Astrinus** [comment]
Thank you. Do you think this issue can be closed?

**Comment by ibell** [comment]
Yes I think so, the docs could perhaps be slightly improved, but its not
critical, I would say close.

**Comment by Astrinus** [comment]
Ok.
