### ISSUE TITLE
dew/bubble densities

### ISSUE THREAD

**Issue by adex987** [CoolProp/CoolProp#908]
I just started using coolprop, MATLAB Wrapper. I have difficulty, how to define bubble and dew properties.

For saturated liquid: I defined "CoolProp.PropsSI('D', 'P', p, 'Q', 0, 'Water')"- this works but for buble, I defined: CoolProp.PropsSI('dl', 'P', p, 'Q', 0, 'Water'), this one didn't works.

How I can define for dew and bubble properties? saturated liquid/ vapor properties are different from bubble/dew.

Thank you,

**Comment by JonWel** [comment]
The bubble density is the one at the limit between liquid and boiling liquid, so it is the last point where the quality is still 0:
``` matlab
dl = CoolProp.PropsSI('D', 'T', 373, 'Q', 0, 'Water')
```
The dew density is the one at the limit between boiling liquid and full gas, so the first point where the quality is one:
``` matlab
dv = CoolProp.PropsSI('D', 'T', 373, 'Q', 1, 'Water')
```

Which is only valid for pure fluid (constant temperature during the phase change).
Using the saturation pressure instead of the temperature gives a more general approach.
