### ISSUE TITLE
AbstractState's behavior with differing capitalization of fluid names seems unpredictable

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#939]
CoolProp seems to care about capitalization with some fluids but not others. In all the following cases, the exceptions mentioned come with the message "Additional information: key [***] was not found in string_to_index_map in JSONFluidLibrary"

	AbstractState s;
	s = AbstractState.factory("?", "R1233zde"); // throws exception
	s = AbstractState.factory("?", "R1233zdE"); // succeeds
	s = AbstractState.factory("?", "R1234ze(z)"); // throws exception
	s = AbstractState.factory("?", "R1234ze(Z)"); // succeeds
	s = AbstractState.factory("?", "R143A"); // succeeds
	s = AbstractState.factory("?", "R143a"); // succeeds

Is this expected behavior?

Using 01/20 nightly build.

**Comment by ibell** [comment]
Yes, the fluid names are case sensitive.  There are some aliases defined
that are of different case, which is why some of those will work.  See for
instance
http://www.coolprop.org/dev/fluid_properties/fluids/R1233zd(E).html#aliases

In all cases, the ALLCAPS of the name will always work, as we have to do
that to make some other languages work (EES).

**Comment by mapipolo** [comment]
Gotcha. Thanks.
