### ISSUE TITLE
CoolProp.Plots import error on windows with CoolProp 5.1.2

### ISSUE THREAD

**Issue by somniumAeternam** [CoolProp/CoolProp#979]
I try to import CoolProp.Plots with 

`from CoolProp.Plots import PropsPlot`

The occuring import error is:

File "C:\Program Files (x86)\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py", line 201
    self._D = BaseDimension(add_SI=0.0, mul_SI=1.0, off_SI=0.0, label='Density',                  symbol=**ur'ρ'**, unit=ur'kg/m³')
 
SyntaxError: invalid syntax

I made the corresponding letters, which are shown for the error, bold.

I'm using Windows 7 64bit and Anaconda 32bit with Python 3.4.

**Comment by jowr** [comment]
It is good to see that someone else is interested in the plots as well. I do not know what the problem is, but the plotting routines seem to be quite fragile and they cause a lot of errors. Maybe it is time to remove the plotting from CoolProp. I will create a new issue for that. 

Sorry, but can you dig into this a little bit? I have not had any problems like this before.

**Comment by somniumAeternam** [comment]
At the moment I don't have the time to dig into the problem in C++. I'm also not very comfortable with that language. The error occurs after updating to CoolProp 5.1.2.
I would really like to keep the plotting somehow. Maybe it is a good idea to decouple it from coolprop and make an extra package for python only. Then you can use matplotlib und create all the nice plots. It could interact more tightly, so that you can adjust the plots and their style better.

I'm using the plot feature for p-h-diagrams and T-s-diagrams. I can plot my calculations directly in these plots, which is very comfortable. In python I can help more ;)

**Comment by jowr** [comment]
OK, I'll have a look myself. However, the problem is for sure on the Python side of things and more specifically it is a Python3 problem. The code runs without problem in Python 2.7, which is the version I use. 
While starting to work on a new GUI as discussed in #980, I have to fix this issue because my target platform is most likely going to be Python3.3 and Windows 64bit.

**Comment by ibell** [comment]
You could of course just use LaTeX rather than a unicode character.  That's a bit more reliable...

**Comment by shrx** [comment]
The issue is in the `ur` string prefix which is not supported in Python3.

**Comment by Hohenheim0** [comment]
I tried to replace every **ur** by **u**(thanks to @shrx) in Common.py and replaced **basestring** by **str** but still have lot of problems...

**Comment by jowr** [comment]
I removed the unicode stuff from the Python files. Could you please confirm that this issue is solved in the very latest sources? @Hohenheim0 @shrx @somniumAeternam

**Comment by jowr** [comment]
I believe that this issue has been solved. Please reopen if necessary. We still have to figure out how to avoid this in the future. I really would like to use unicode for plotting...
