### ISSUE TITLE
Javascript Interface

### ISSUE THREAD

**Issue by e-lead** [CoolProp/CoolProp#990]
hi, 

just want to test Javscript Interface of Coolprop and found  http://www.coolprop.dreamhosters.com:8010/unstable/Javascript/
But it is not working.

**Comment by jowr** [comment]
You are obviously right. I tried several versions and the latest one produces
```
still waiting on run dependencies: coolprop-latest.js:1:2512
dependency: memory initializer coolprop-latest.js:1:2512
dependency: al coolprop.js.mem
```
I remember that @ibell changed the wrapper for the 5.1.2 release and it looks like the changes did not make it to the release script. 

Instead of using a single file, one now has to include 2 files `coolprop.js` and `coolprop.js.mem`, but then it works. I'll update the release script and the example `index.html`.

**Comment by jowr** [comment]
By the way, how did you find that link? Please use http://coolprop.sourceforge.net/jscript/ or http://www.coolprop.dreamhosters.com/binaries/Javascript/ in the future.

**Comment by jowr** [comment]
The example at http://www.coolprop.sourceforge.net/jscript/index.html works again.

**Comment by ibell** [comment]
Are you sure?  It doesn't for me...

**Comment by e-lead** [comment]
It also doesn´t work for me

**Comment by jowr** [comment]
I just tried with a different computer and it works. Please make sure you refresh your browser.

**Comment by jowr** [comment]
... and please use http://www.coolprop.sourceforge.net/jscript/index.html

**Comment by e-lead** [comment]
hi now it works and i found the problem: there´s no error handling on input fields. If I wanna calculate density in a low temperature (about 10K) it throws an exeception and this  makes sense in physically background:)
thank you very much.
